### ISSUE TITLE
如何以lib的方式集成到Android和flutter里面

### ISSUE THREAD

**Issue by DennisJu007** [jenly1314/ZXingLite#104]
如何以lib的方式集成到Android和flutter里面，能否提供一个library库

**Comment by jenly1314** [comment]
Flutter混合开发和源生Android开发集成方式可以是一样的，只不过你需要单独的去实现Android和iOS的扫码功能。

**Comment by DennisJu007** [comment]
嗯嗯只能copy了一份源码进去自己修改
