### ISSUE TITLE
识别本地图片问题

### ISSUE THREAD

**Issue by w2xx** [jenly1314/ZXingLite#11]
我有一张图片，直接导入本地图，识别不出来，但是打开图片，用照相机预览扫描又可以扫出来，不知道是什么原因

**Comment by jenly1314** [comment]
识别不出来一般有两种情况；
一种是：可识别度不够、显示的一维码、二维码区域所占比例了或识别度不够导致解析失败。
另一种是：图片文件太大了、在识别的时候提前已做过适当的压缩，暂时还没有找到一个完美的比例值。

**Comment by w2xx** [comment]
图片文件不大，244kb。我换了个基于zbar的库，导入这个图就可以识别的出来，我也很郁闷。。预览图片也能识别，就是导入本地图识别不出来
