### ISSUE TITLE
SingleActivity扫描完成后应用被finish

### ISSUE THREAD

**Issue by Zheng-Shuo** [jenly1314/ZXingLite#110]
作者你好，我遇到个问题，就是我的应用是但Activity的我初始化CaptureHelper时出入Fragment然后我看源码里面出结果后会获取道Fragment的Activity然后给他finish掉，这样的话我的应用整个就被关闭了，请问这个问题应该如何处理，我现在的做法是开启连扫，在获得一个结果之后自己关闭当前的Fragment来避免finish整个应用，我不知道是我设置的问题还是怎样，麻烦作者回复一下谢谢

**Comment by jenly1314** [comment]
```java
/**
 * 扫码结果回调
 * return 返回true表示拦截，将不自动执行后续逻辑，为false表示不拦截，默认不拦截
 */
public boolean onResultCallback(java.lang.String result)
```
你可以通过onResultCallback方法返回true，自己处理扫码结果回调

**Comment by Zheng-Shuo** [comment]
原来如此，非常感谢，这块看漏掉了
