### ISSUE TITLE
如何长期停留在扫码界面

### ISSUE THREAD

**Issue by jiangkaifang** [jenly1314/ZXingLite#113]
感谢作者的分享！

我发现停留在扫码界面时间长了activity会被 Finishing activity due to inactivity，请问如何才能避免。我们的需求是需要长期停留在扫码界面

**Comment by jenly1314** [comment]
因为扫码一般都是瞬间完成的一个操作，如果长期停留在扫码界面，只会增加手机电量消耗。所以在扫码界面有个延时任务，现在是5分钟会自动关闭扫码界面，具体参见：**InactivityTimer ** 类

**Comment by jiangkaifang** [comment]
有办法可以关闭掉这个任务吗？我们现在的需求就是长期停留在扫描界面
