### ISSUE TITLE
识别相册二维码，带logo 的识别不了

### ISSUE THREAD

**Issue by lichaohuilala** [jenly1314/ZXingLite#114]
CodeUtils.parseQRCode(path);
CodeUtils.parseCode(path);
都试了，还是不行 ！ 求解答

**Comment by lichaohuilala** [comment]
扫描就可以，识别本地图片，带logo的不行，不带logo的可以使用！

**Comment by lichaohuilala** [comment]
![79901fedda868387d07e47e0d1e1f61](https://user-images.githubusercontent.com/27003184/99532920-064c2a00-29e0-11eb-9e3e-1ed698a02e19.png)

**Comment by bufanx** [comment]
你好，识别本地图片传入的bitmappath是什么

**Comment by jenly1314** [comment]
#69
