### ISSUE TITLE
Fragment不支持缩放

### ISSUE THREAD

**Issue by BaiMingxu1** [jenly1314/ZXingLite#115]
第一个问题：Fragment不支持缩放求帮助,  
第二个问题：我的BaseFragment继承CaptureFragment启动程序直接崩溃报错：
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.king.zxing.CaptureHelper.onCreate()' on a null object reference

**Comment by jenly1314** [comment]
如果想要自定义扫码界面又想使用自己的 **BaseFragment** 基类，不用继承**CaptureActivity** 或 **CaptureFragment** ，请使用 **README** 中所说到的第三种方式实现，**自定义Fragment** 的方式可参见 [CustomActivity](https://github.com/jenly1314/ZXingLite/blob/master/app/src/main/java/com/king/zxing/app/CustomActivity.java) 写一个自定义的Fragment，然后Fragment要支持缩放，只需将View的**onTouch** 事件交由 **CaptureHelper** 处理即可。
示例：
```java
        surfaceView.setOnTouchListener(new OnTouchListener() {
            @Override
            public boolean onTouch(View v, MotionEvent event) {
                //触摸事件交由 CaptureHelper处理
                return getCaptureHelper().onTouch(event);
            }
        });
```

**Comment by BaiMingxu1** [comment]
谢谢您，已经解决。
