### ISSUE TITLE
这个图片识别有问题，帮忙看一下，谢谢！

### ISSUE THREAD

**Issue by rameble** [jenly1314/ZXingLite#119]
我在华为p30和p30 pro上安装了ZXingLite,使用默认扫描方式扫描附件中的图片，
![test](https://user-images.githubusercontent.com/30107684/102567008-97b3d680-411b-11eb-8183-b8e002228895.png)

手机距离这个要扫描的图片一米远左右，正确结果应该是一个json字符串，如下：
 {"content":"YFot4qaz9/Mny******************

但扫描成功几次后，就会出一次错误，得到一个随机的八位数字。  

出错概率有时候扫描五六次就出错，有时候几十次后出错。手机离二维码越远，好像出错概率越高。

请问如果解决这个问题。 谢谢。

**Comment by jenly1314** [comment]
识别错误的我猜测可能性应该是识别成条形码了，如果你只有扫二维码的需求可以配置仅识别二维码，这样可以减少出现的概率。或者你也可以使用最新版，测试看是否有此问题。

**Comment by rameble** [comment]
非常感谢，问题已解决。 配置仅识别.QR_CODE，问题解决。
