### ISSUE TITLE
华为7.1.2设备上数组越界崩溃

### ISSUE THREAD

**Issue by jaime1990** [jenly1314/ZXingLite#122]
> 设备：HUAWEI - VOG-AL00（7.1.2）

`
---java.lang.ArrayIndexOutOfBoundsException: length=460800; index=461519 
com.king.zxing.DecodeHandler.com.google.zxing.PlanarYUVLuminanceSource  buildPlanarYUVLuminanceSource(byte[],int,int,boolean)(DecodeHandler.java:199) 
com.king.zxing.DecodeHandler.void decode(byte[],int,int,boolean,boolean)(DecodeHandler.java:97) 
com.king.zxing.DecodeHandler.void handleMessage(android.os.Message)(DecodeHandler.java:69) 
android.os.Handler.dispatchMessage(Handler.java:102) 
android.os.Looper.loop(Looper.java:154) 
com.king.zxing.DecodeThread.void run()(DecodeThread.java:118)
`

辛苦大佬帮忙看看。谢谢~

**Comment by jenly1314** [comment]
请提供ZXingLite使用版本和集成相关代码示例或更多日志信息

**Comment by jaime1990** [comment]
引入版本： `com.king.zxing:zxing-lite:1.1.9-androidx`

![image](https://user-images.githubusercontent.com/11324995/103188062-ea527700-4901-11eb-9260-14a8d8df71ed.png)

根据第三种使用方式，在我的Activity（继承自FragmentActivity，自定义Layout）里面通过`CaptureHelper`来实现扫码，Activity的对应生命周期中也同步调用了CaptureHelper的生命周期方法。

**Comment by jaime1990** [comment]
目前仅在华为7.1.2设备上出现。

**Comment by jaime1990** [comment]
大佬，请问这个问题可还有解？

**Comment by jenly1314** [comment]
从你贴的日志信息，只能看出是处理YUV数据时下标越界了，没有相关的设备，或者没有更详细的日志，我也无法定位到导致越界的根本原因。
如果你的项目是基于AndroidX开发的，你也可是使用最新版本。可能需要您重新按照新本的步骤集成一遍，因为是重构版本，与之前的 **v1.x** 的实现方式不一样。

**Comment by jaime1990** [comment]
> 从你贴的日志信息，只能看出是处理YUV数据时下标越界了，没有相关的设备，或者没有更详细的日志，我也无法定位到导致越界的根本原因。
> 如果你的项目是基于AndroidX开发的，你也可是使用最新版本。可能需要您重新按照新本的步骤集成一遍，因为是重构版本，与之前的 **v1.x** 的实现方式不一样。

OK了解了，多谢， 后面抽空升级后再看看！
