### ISSUE TITLE
Camera is being used after Camera.release() was called

### ISSUE THREAD

**Issue by EthanCo** [jenly1314/ZXingLite#124]
1.1.9-androidx版本

java.lang.RuntimeException:Camera is being used after Camera.release() was called
        android.hardware.Camera.native_getParameters(Native Method)
        android.hardware.Camera.getParameters(Camera.java:2199)
        com.king.zxing.DecodeHandler.handleAutoZoom(SourceFile:4)
        com.king.zxing.DecodeHandler.decode(SourceFile:24)
        com.king.zxing.DecodeHandler.handleMessage(SourceFile:3)
        android.os.Handler.dispatchMessage(Handler.java:107)
        android.os.Looper.loop(Looper.java:213)
        com.king.zxing.DecodeThread.run(SourceFile:4)

**Comment by EthanCo** [comment]
附上Bugly页面追踪记录，QrCodeActivity就是扫码的页面
2021-01-09 16:10:27 QrCodeActivity onCreated
72021-01-09 16:10:27 QrCodeActivity onResumed
82021-01-09 16:10:30 QrCodeActivity onPaused
92021-01-09 16:10:30 QrCodeActivity onCreated
102021-01-09 16:10:30 QrCodeActivity onResumed

**Comment by EthanCo** [comment]
感觉是调用DecodeHandler.handleAutoZoom的时候，Camera已经release掉了

**Comment by EthanCo** [comment]
累计已经出现1000多次了，每天大概出现0-2次

**Comment by jenly1314** [comment]
你可以通过关闭自动缩放功能试试，示例如下：
```java
    getCaptureHelper().supportAutoZoom(false)；
```
