### ISSUE TITLE
支持DM格式的二维码么

### ISSUE THREAD

**Issue by DDjason** [jenly1314/ZXingLite#126]
二维码为data matrix

**Comment by jenly1314** [comment]
支持的，请参见 [**DecodeFormatManager**](https://github.com/jenly1314/ZXingLite/blob/master/lib/src/main/java/com/king/zxing/DecodeFormatManager.java) 和 [**DecodeConfig**](https://github.com/jenly1314/ZXingLite/blob/master/lib/src/main/java/com/king/zxing/DecodeConfig.java)，里面有详细说明

配置示例：
```java
 decodeConfig.setHints(DecodeFormatManager.TWO_DIMENSIONAL_HINTS);
```
你可以根据具体需求去自定义配置想要支持的格式。

具体配置可以参见 **README** 中 **decodeConfig.setHints**相关示例，或查看 [**app**](https://github.com/jenly1314/ZXingLite/tree/master/app) 中的示例

**Comment by DDjason** [comment]
![微信图片_20210119075643](https://user-images.githubusercontent.com/16483208/104972657-56218e80-5a2d-11eb-8172-7466e8f8b264.png)


> 支持的，请参见 [**DecodeFormatManager**](https://github.com/jenly1314/ZXingLite/blob/master/lib/src/main/java/com/king/zxing/DecodeFormatManager.java) 和 [**DecodeConfig**](https://github.com/jenly1314/ZXingLite/blob/master/lib/src/main/java/com/king/zxing/DecodeConfig.java)，里面有详细说明
> 
> 配置示例：
> 
> ```java
>  decodeConfig.setHints(DecodeFormatManager.TWO_DIMENSIONAL_HINTS);
> ```
> 
> 你可以根据具体需求去自定义配置想要支持的格式。
> 
> 具体配置可以参见 **README** 中 **decodeConfig.setHints**相关示例，或查看 [**app**](https://github.com/jenly1314/ZXingLite/tree/master/app) 中的示例
