### ISSUE TITLE
无法指定前置摄像头CameraConfig设置->new CameraSelector.Builder().requireLensFacing(CameraSelector.LENS_FACING_FRONT)

### ISSUE THREAD

**Issue by Obabull** [jenly1314/ZXingLite#128]
@Override
    public void initCameraScan() {
        super.initCameraScan();
//指定前置摄像头
        CameraConfig cameraConfig = new CameraConfig();
        cameraConfig.options( new CameraSelector.Builder().requireLensFacing(CameraSelector.LENS_FACING_FRONT));

        //获取CameraScan，扫码相关的配置设置。CameraScan里面包含部分支持链式调用的方法，即调用返回是CameraScan本身的一些配置建议在startCamera之前调用。
        getCameraScan()
                .setPlayBeep(true)//设置是否播放音效，默认为false
                .setVibrate(false)//设置是否震动，默认为false
                 .setCameraConfig(cameraConfig)//设置相机配置信息，CameraConfig可覆写options方法自定义配置
                .setNeedAutoZoom(false)//二维码太小时可自动缩放，默认为false
                .setNeedTouchZoom(false)//支持多指触摸捏合缩放，默认为true
                .setOnScanResultCallback(this)//设置扫码结果回调，需要自己处理或者需要连扫时，可设置回调，自己去处理相关逻辑
                .setAnalyzer(new MultiFormatAnalyzer(new DecodeConfig()))//设置分析器,DecodeConfig可以配置一些解码时的配置信息，如果内置的不满足您的需求，你也可以自定义实现，
                .setAnalyzeImage(true);//设置是否分析图片，默认为true。如果设置为false，相当于关闭了扫码识别功能
        //初始化解码配置
        DecodeConfig decodeConfig = new DecodeConfig();
        decodeConfig.setHints(DecodeFormatManager.ONE_DIMENSIONAL_HINTS)//如果只有识别二维码的需求，这样设置效率会更高
                .setFullAreaScan(false)//设置是否全区域识别，默认true
                .setAreaRectRatio(0.9f)//设置识别区域比例，默认0.9，设置的比例最终会在预览区域裁剪基于此比例的一个矩形进行扫码识别
                .setAreaRectVerticalOffset(0)//设置识别区域垂直方向偏移量，默认为0，为0表示居中，可以为负数
                .setAreaRectHorizontalOffset(0);//设置识别区域水平方向偏移量，默认为0，为0表示居中，可以为负数

    }

**Comment by jenly1314** [comment]
可以设置的，**CameraConfig** 自定义配置的写法不是你这样的用的。

设置前置摄像头示例如下：
```java
        CameraConfig cameraConfig = new CameraConfig(){
            @NonNull
            @Override
            public CameraSelector options(@NonNull CameraSelector.Builder builder) {
                return new CameraSelector.Builder()
                        .requireLensFacing(CameraSelector.LENS_FACING_FRONT).build();
            }
        };

        getCameraScan().setCameraConfig(cameraConfig);
```

**Comment by Obabull** [comment]
哈哈 谢谢大佬

**Comment by CandyTek** [comment]
谢谢大佬，帮大忙了。大佬可以把这个例子写在一些帮助里

**Comment by CandyTek** [comment]
> 可以设置的，**CameraConfig** 自定义配置的写法不是你这样的用的。
> 
> 设置前置摄像头示例如下：
> 
> ```java
>         CameraConfig cameraConfig = new CameraConfig(){
>             @NonNull
>             @Override
>             public CameraSelector options(@NonNull CameraSelector.Builder builder) {
>                 return new CameraSelector.Builder()
>                         .requireLensFacing(CameraSelector.LENS_FACING_FRONT).build();
>             }
>         };
> 
>         getCameraScan().setCameraConfig(cameraConfig);
> ```

谢谢大佬，帮大忙了。大佬可以把这个例子写在一些帮助里
