### ISSUE TITLE
连扫的情况会卡主线程?

### ISSUE THREAD

**Issue by manondidi** [jenly1314/ZXingLite#129]
连扫的情况 在执行里面有耗时操作 会卡主线程

**Comment by jenly1314** [comment]
你代码怎么写的，方便贴出示例吗？

**Comment by manondidi** [comment]
根据你的源码 连扫的回调都在主线程里,所以连扫时候 做耗时操作当然会卡了
然后 我发现了camerax 版本中的bug
 如果在analyze 回调里面做了许多处理 会导致oom
应该是camerax的bug 这个我在 stackoverflow上看到过,
会出现大量的 rsmessageThread 最后 线程池爆掉,

**Comment by manondidi** [comment]
你的场景也是能用的 用于简单的扫码, 就是跳转`去扫码 扫完 关闭页面回调,没问题的
但是如果有 持续在某个页面连扫, camerax 是有很大可能性会oom.目前来看camerax 官方没有修复这个问题.
