### ISSUE TITLE
想问下是否支持自动对焦

### ISSUE THREAD

**Issue by lightsmeki** [jenly1314/ZXingLite#130]
android手机测试的时候，不同手机反应差很多，如果不用手指拖动放大缩小画面，部分手机很久都无法识别二维码，用双指放大后基本都能很快识别。
想问下在不同手机自动调焦这块有什么接口可以开放或者做的吗？希望能不用自己去拖动直接能够自动调焦放大缩小

**Comment by lightsmeki** [comment]
getCameraScan这个方法我看了下代码里是不是没调用啊？哪怕我配置了也没用诶？

**Comment by w382285328** [comment]
> getCameraScan这个方法我看了下代码里是不是没调用啊？哪怕我配置了也没用诶？

兄弟 对焦问题解决了吗？ 我也遇到这个问题了

**Comment by feisher** [comment]
兄弟 对焦问题解决了吗？1.1.9之前的使用camera库的对焦没问题，换车最新的2.0.2 就不行了，如果解决了请更新下留言，持续关注中

**Comment by feisher** [comment]
@w382285328 @lightsmeki 下拉代码修改 DefaultCameraScan类233行代码， ImageAnalysis 添加.setTargetResolution(new Size(1920, 1080))，，可以实现二维码较小 快速识别，虽然没有1.1.9的缩放流畅效果，但识别速度有提升

**Comment by jenly1314** [comment]
[#221](https://github.com/jenly1314/ZXingLite/issues/221#issuecomment-1573502160)
