### ISSUE TITLE
使用经典模块操作，导航栏隐藏时，ViewfinderView实际的框没有居中

### ISSUE THREAD

**Issue by Vander-liu** [jenly1314/ZXingLite#132]
![device-2021-01-30-145206](https://user-images.githubusercontent.com/16666953/106349897-b4435100-630c-11eb-9dde-35ec06123fb1.png)

导致自定义的“轻触照亮”的按钮产生偏移

**Comment by Vander-liu** [comment]
https://imgchr.com/i/yki1yT

**Comment by Vander-liu** [comment]
```
    @Override
    protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
        super.onMeasure(widthMeasureSpec, heightMeasureSpec);
        //扫码框默认居中，支持利用内距偏移扫码框
        int leftOffset = (screenWidth - frameWidth) / 2 + getPaddingLeft() - getPaddingRight();
        int topOffset = (screenHeight - frameHeight) / 2 + getPaddingTop() - getPaddingBottom();
        frame = new Rect(leftOffset, topOffset, leftOffset + frameWidth, topOffset + frameHeight);
    }
```

**Comment by Vander-liu** [comment]
怀疑是直接使用屏幕宽高去计算frame，而不是使用View的宽高去计算造成的

**Comment by Vander-liu** [comment]
先提供个临时解决方案：
```
 viewfinderView.post {
            val width = viewfinderView.width
            val height = viewfinderView.height
            val widthField = viewfinderView.javaClass.getDeclaredField("screenWidth")
            widthField.isAccessible = true
            val heightField = viewfinderView.javaClass.getDeclaredField("screenHeight")
            heightField.isAccessible = true
            widthField.setInt(viewfinderView, width)
            heightField.setInt(viewfinderView, height)
            viewfinderView.requestLayout()
        }
```

**Comment by jenly1314** [comment]
看你贴的部分代码，你应该使用的是 **v1.x** 版本，对于**ViewfinderView**而言，建议 **ViewfinderView** 铺满屏幕。因为涉及到Camera 预览适配相关（通过遍历Camera配置找到最匹配的预览大小）。如果要居中记得  别设置**ViewfinderView**的padding，因为padding也会影响框的位置。

**Comment by Vander-liu** [comment]
@jenly1314  使用ViewfinderView时，是选择铺满屏幕的（match_parent）

因为在包含底部导航栏的情况下，此时横屏状况获取的ScreenWidth是包含导航栏的。

而图片中出现的场景，是因为此时设置属性将导航栏隐藏。

理论上我理解ViewfinderView只是定义扫描二维码的扫描框样式的View，所以内置样式应该和View宽高相关，而不是和屏幕宽高相关。

**Comment by Vander-liu** [comment]
版本是1.x最后一个版本

出现该问题，（横屏状态下）获取的屏幕宽高，包含的导航栏
因为设置了导航栏隐藏，所以在显示时

ViewFinderView#onMeasure
```
    @Override
    protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
        super.onMeasure(widthMeasureSpec, heightMeasureSpec);
        //扫码框默认居中，支持利用内距偏移扫码框
        int leftOffset = (screenWidth - frameWidth) / 2 + getPaddingLeft() - getPaddingRight();
        int topOffset = (screenHeight - frameHeight) / 2 + getPaddingTop() - getPaddingBottom();
        frame = new Rect(leftOffset, topOffset, leftOffset + frameWidth, topOffset + frameHeight);
    }
```
根据屏幕的宽度计算出现了偏移

**Comment by jenly1314** [comment]
导航栏是否显示不应该影响预览的大小，如果影响了，你这里的 **match_parent** 并不表示真正的铺满了屏幕。
你可能看漏了，请在 **AndroidManifest** 中将你扫码的  **Activity** 添加 **CaptureTheme** 主题配置，如下：
```xml
    <activity
        android:name=".YourCaptureActivity"
        android:theme="@style/CaptureTheme"/>
       
```

**Comment by Vander-liu** [comment]
@jenly1314  应该不是Theme的问题，不过还是很感谢，等有时间我用Sample复现下问题

复现步骤：
（1）设置-全面屏-经典导航键
（2）横屏状态

等下我看看Sample里面能不能复现

@jenly1314  谢啦~

**Comment by Vander-liu** [comment]
@jenly1314  我刚刚下载了源码，发现问题确实是存在的。

在最新v2.x版本，由于ViewfinderView的计算Frame方式变更，所以问题才没有复现

v2.x  ViewFinderView
```
    @Override
    protected void onSizeChanged(int w, int h, int oldw, int oldh) {
        super.onSizeChanged(w, h, oldw, oldh);
        initFrame(w,h);
    }

```
v1.x ViewFinderView
```
    @Override
    protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
        super.onMeasure(widthMeasureSpec, heightMeasureSpec);
        //扫码框默认居中，支持利用内距偏移扫码框
        int leftOffset = (screenWidth - frameWidth) / 2 + getPaddingLeft() - getPaddingRight();
        int topOffset = (screenHeight - frameHeight) / 2 + getPaddingTop() - getPaddingBottom();
        frame = new Rect(leftOffset, topOffset, leftOffset + frameWidth, topOffset + frameHeight);
    }
```

可以发现v2.x中ViewFinderView计算Frame时使用的ViewFinderView本身的宽高计算出Frame,而v1.x中使用screenWidth、screenHeight来计算Frame

所以问题出在这里。

**Comment by jenly1314** [comment]
感谢耐心测试并反馈、我用 **v1.x** 验证了下，确实有此问题。因为 **v2.x** 基于CameraX重构了，使用方式方式有所变更，不过整体思想还是一样的，所以 **v1.x**可能不再继续维护发新版本。

你目前有一下几种方案解决此问题：
1. 就是你所说的通过反射的方式。
2. ViewFinderView 本质上只是给用户提供扫码的视觉效果，与扫码识别的逻辑处理是分开的。你可以重新定义一个ViewFinderView 放在布局里面使用，详细说明参见 **README** 中的布局示例下方的说明。
3. 升级至 **v2.x** 版本。
4. 通过GitPack引入依赖，这种方式要提交代码，如果有需要跟我说下。

**Comment by Vander-liu** [comment]
最开始我尝试自定义ViewFinderView，但是发现处理扫描的CaptureHelper也得调整，后来放弃了。

等CameraX出稳定版，到时候切到v2.x

在这期间，直接先用反射应该没什么问题，后续如果有人也遇到类似情况，可以参考反射方案

最后感谢作者，感觉耐心回答
