### ISSUE TITLE
2.0.2版本二维码太小的时候不会自动放大，已设置自动缩放，但没有效果

### ISSUE THREAD

**Issue by feisher** [jenly1314/ZXingLite#136]
val decodeConfig = DecodeConfig()
        decodeConfig.setHints(DecodeFormatManager.QR_CODE_HINTS)
            .setFullAreaScan(false) //设置是否全区域识别，默认false
            .setAreaRectRatio(0.8f)
            .setAreaRectVerticalOffset(0)
            .setAreaRectHorizontalOffset(0)
        cameraScan
            .setVibrate(true)
            .setNeedAutoZoom(true)
            .setAnalyzer(MultiFormatAnalyzer(decodeConfig))
已经设置自动缩放，但没有效果

**Comment by majiankang** [comment]
同上

**Comment by a453826252** [comment]
同上，2.1.1版本

**Comment by lihongwen1** [comment]
同上，2.4.0版本

**Comment by Allen8Lee** [comment]
您发送的邮件我已收到。

**Comment by jenly1314** [comment]
[#221](https://github.com/jenly1314/ZXingLite/issues/221#issuecomment-1573502160)

**Comment by wufan-hash** [comment]
@jenly1314 这个自动放大现在不支持了嘛，只能手动放大缩小了？

**Comment by jenly1314** [comment]
> @jenly1314 这个自动放大现在不支持了嘛，只能手动放大缩小了？

[CameraScan](https://github.com/jenly1314/CameraScan) 独立出去维护之后就移除了自动缩放功能，即：3.0.0以上版本不支持了；之前的2.x版本是支持的。
