### ISSUE TITLE
OOM  addLogo()   Bitmap bitmap = Bitmap.createBitmap(srcWidth, srcHeight, Bitmap.Config.ARGB_8888);

### ISSUE THREAD

**Issue by LiWeiQiangAndroid** [jenly1314/ZXingLite#137]
这里会发生OOM

**Comment by jenly1314** [comment]
你生成多大的二维码？

**Comment by LiWeiQiangAndroid** [comment]
200*200 单位dp

**Comment by jenly1314** [comment]
> 生成带logo的二维码也就创建两张位图，感觉不至于，不知道你传的logo图片有多大？你可以先尝试使用 **Bitmap.Config.ARGB_4444** 
[Demo](https://github.com/jenly1314/ZXingLite/app)中生成的二维码宽高就 400 * 400了，后续我抽空生成更大的二维码试下。

**Comment by LiWeiQiangAndroid** [comment]
java.lang.OutOfMemoryError

Failed to allocate a 1440012 byte allocation with 877928 free bytes and 857KB until OOM

看上报的异常都是在后台的，系统 android5.1-7.0
