### ISSUE TITLE
某些二维码扫不出结果

### ISSUE THREAD

**Issue by wangshufu** [jenly1314/ZXingLite#138]
你好,我的这个二维码扫不出结果,查了别的库也是扫不出,但是我用微信,这些能够扫出来,不知道是什么原因

**Comment by wangshufu** [comment]
![image](https://user-images.githubusercontent.com/20333012/112783140-389e2000-9081-11eb-8bb7-75cbefa0c47b.png)

**Comment by oubaoyi** [comment]
使用华为扫码吧

**Comment by ppg408331701** [comment]
微信会自己纠错的，但是他不开源，不知道怎么做的

**Comment by jenly1314** [comment]
见 #69  

如果你只是基本扫码的需求，**ZXingLite**完全能满足你。如果你对扫码有着比较严格或者更加苛刻的要求，比如：变形码，比例不规范的码，一张复杂的大图上有个很小的码等场景，**ZXingLite**可能并不能完全满足你的需求。你可以尝试使用 [**MLKit**](https://hub.fastgit.org/jenly1314/MLKit)中的**mlkit-barcode-scanning**，**mlkit-barcode-scanning** 的识别率相对来说会更高。

**Comment by tanranran** [comment]
> 微信会自己纠错的，但是他不开源，不知道怎么做的

开源了
https://docs.opencv.org/master/d5/d04/classcv_1_1wechat__qrcode_1_1WeChatQRCode.html

**Comment by tanranran** [comment]
> 微信会自己纠错的，但是他不开源，不知道怎么做的

开源了
https://docs.opencv.org/master/d5/d04/classcv_1_1wechat__qrcode_1_1WeChatQRCode.html

**Comment by chenxiaofei910714** [comment]
> 见#69
> 
> 如果你只是基本码的需求，**ZingXingLite**完全可以满足你的需求。小的码等场景，**ZXingLite**可能并不能完全满足你的需求。你可以尝试使用[**mLKit**](https://hub.fastgit.org/jenly1314/MLKit)中的**mlkit条形码扫描**，**mlkit条形码扫描**的识别率相对来说会更高。

引入了你的mlKit依赖之后，开启混淆后就会一直报空指针，不开就正常
