### ISSUE TITLE
如何得到二维码、条形码的坐标

### ISSUE THREAD

**Issue by TheWindMeanFar** [jenly1314/ZXingLite#145]
有个需求，在扫码时，检测到二维码、条码的时候，要在码的区域显示一个标识。只要能得到识别出来的二维码的坐标，就可以显示了。

onScanResultCallback(Result result) 此方法中的 result.getResultPoints()，二维码返回 4 个点，条形码返回 2 个点，我猜想这应该就是二维码四个定位点的坐标，但实际测试中，这四个点的坐标扑朔迷离，并不总是正确的样子。

求助，如何获得正确的二维码的位置坐标。

**Comment by jenly1314** [comment]
result.getResultPoints() 确实是识别结果的坐标，不过是针对于分析图像识别区域的相对坐标，并非预览的坐标。
想要获得正确的坐标，就需要根据你的识别区域对应的配置，去换算识别结果的坐标在整个分析图像上坐标的位置，然后再换算得到相机预览的位置。

**Comment by TheWindMeanFar** [comment]
琢磨许久未果，我又来求助了，如何判断条码的方向？

前提：手机是竖屏扫码，不旋转。
现在二维码，横向的条码，我可以准备标出它的位置了。
二维码是四方形，转动之后也能标出位置。

但是条码的情况就不同了，顺时针转动：

0°、360°（常态）：横向，头左尾右。横坐标：头小尾大。扫码结果返回的 result.getResultMetadata() : null

90° ：竖向，头上尾下。                      横坐标：头小尾大。                           result.getResultMetadata() : null

180°：横向，头右尾左。                     横坐标：头大尾小。                           result.getResultMetadata() : {ORIENTATION=180}

270°：竖向，头下尾上。                     横坐标：头大尾小。                           result.getResultMetadata() : {ORIENTATION=180}

而且条码转为竖向时，从输出的坐标的来看，其坐标系似乎也发生了转动，像是逆时针转了 90°。
综合以上得到的条件，无法正确判断出条码的方向。

**Comment by jenly1314** [comment]
**DecodeConfig** 中有个 **setSupportVerticalCode** 方法，你是否有设置过，这个方法会增强对垂直条码的识别，但同时可能会旋转识别分析的图片

**Comment by TheWindMeanFar** [comment]
有哦，我开了支持垂直

**Comment by jenly1314** [comment]
** MultiFormatAnalyzer ** 中有一段关于旋转识别分析图片的代码，大致如下
```java
              //前面是没旋转之前正常的识别相关代码，省略...

              //如果结果为空并且支持垂直识别，则将分析的图像进行旋转处理后再进行识别
               if(rawResult == null && mDecodeConfig.isSupportVerticalCode()){
                    byte[] rotatedData = new byte[data.length];
                    for (int y = 0; y < dataHeight; y++) {
                        for (int x = 0; x < dataWidth; x++){
                            rotatedData[x * dataHeight + dataHeight - y - 1] = data[x + y * dataWidth];
                        }
                   }
                   //旋转后的识别处理
                   rawResult = decodeInternal(new PlanarYUVLuminanceSource(rotatedData,dataHeight,dataWidth,top,left,height,width,false),mDecodeConfig.isSupportVerticalCodeMultiDecode());
               
               }
```
你可以通过 判定**rawResult** 是什么时候不为空的，来确定识别结果的位置是否有旋转过。

**Comment by wmgm183** [comment]
楼主 分享下你的 这个 onScanResultCallback 方法呀
