### ISSUE TITLE
为什么 setAnalyzeAreaRect 设置识别区域后，识别率直线下降

### ISSUE THREAD

**Issue by TheWindMeanFar** [jenly1314/ZXingLite#146]
一切都是需求，需要修改扫码框的大小，所以需要修改识别区域。

我修改之后打印 decodeConfig.toString() 可以看到，输出的左上角坐标和右下角坐标与肉眼可见的那个扫码框是重叠的，说明分析区域没有设偏，但是为什么识别率会直线下降。

小米 5S，Android 8，有实体导航键，1080 x 1920，识别率有所下降，勉强还能扫。
红米 K30，Android 11，是虚拟导航键，1080 x 2400，很难扫到了。
小米11，Android 11，是虚拟导航键，2K 分辨率，几乎扫不到。

默认的配置，不设置 setAnalyzeAreaRect 就正常，这是咋回事呢

**Comment by jenly1314** [comment]
**setAnalyzeAreaRect** 是针对于特殊需求预留的，需要明确需要分析的图像大小后，通过换算得到想要的区域。并不适用于去适配所有手机的场景，因为相机预览和真正分析的图片宽高并非绝对一致的，肉眼所见的只是预览图像的大小，并不是需要分析图像的大小；而且在识别时，如果是非全屏识别的情况下，只是截取需要分析图像的一部分区域进行识别。手机型号不同，分析的图像宽高就可能不同，区域定位不对，自然就会影响到识别。

#### 在 [DecodeConfig](https://github.com/jenly1314/ZXingLite/blob/master/lib/src/main/java/com/king/zxing/DecodeConfig.java) 中有相关的说明
##### 识别区域可设置的方式有如下几种：
* **setFullAreaScan(boolean)** 设置是否支持全区域扫码识别，优先级比识别区域高
* **setAnalyzeAreaRect(Rect)** 设置需要分析识别区域，优先级比识别区域比例高，当设置了指定的分析区域时，识别区域比例和识别区域偏移量相关参数都将无效  
* **setAreaRectRatio(float)** 设置识别区域比例，默认**DEFAULT_AREA_RECT_RATIO**，设置的比例最终会在预览区域裁剪基于此比例的一个矩形进行扫码识别，优先级最低

**Comment by jenly1314** [comment]
记得 **CameraX** 中有一段关于 **ImageAnalysis** 配置**TargetResolution** 的相关说明；大意是在综合考虑性能和图片质量相关因素的前提下，分析的图像最大不会超过 **1080p**。 所以你所测试的小米11的 **mTargetSize** 超过了1080。

**mTargetSize** 只是预期目标分辨率大小，实际分析的图像的分辨率宽高可以从**ImageProxy**中获取。你可以直接在[AreaRectAnalyzer](https://github.com/jenly1314/ZXingLite/blob/master/lib/src/main/java/com/king/zxing/analyze/AreaRectAnalyzer.java)中看到分析图像的实际宽高。
