### ISSUE TITLE
角度倾斜时，二维码扫描不到结果

### ISSUE THREAD

**Issue by huaxiaos** [jenly1314/ZXingLite#147]
请问下，如果不是从正面扫二维码，而是从侧面扫描二维码，基本就很难扫到结果，这个问题怎么解决

![image](https://user-images.githubusercontent.com/8043228/122169597-2b3e4800-ceb0-11eb-9a74-fc6cac66b897.png)

**Comment by jenly1314** [comment]
见 #69
