### ISSUE TITLE
微信二维码引擎OpenCV开源，有集成的计划吗？

### ISSUE THREAD

**Issue by Ramblerchris** [jenly1314/ZXingLite#148]

**Comment by jenly1314** [comment]
* 抱歉，最近一段时间比较忙，没有太多空闲时间去移植OpenCV。
* 目前已有 **ZXingLite** 和 **MLKit** 两个开源项目拥有扫码识别的能力，基本能满足所有扫码相关场景。

**Comment by jenly1314** [comment]
[WeChatQRCode](https://github.com/jenly1314/WeChatQRCode)
