### ISSUE TITLE
2.1.0集成一直崩溃，CameraX is not configured properly

### ISSUE THREAD

**Issue by huyi3211** [jenly1314/ZXingLite#149]
小米8，系统是Android10，依赖2.1.0版本，使用的是demo中QRCodeActivity的集成方式，一直崩溃，报错信息：CameraX is not configured properly. The most likely cause is you did not include a default implementation in your build such as 'camera-camera2'.

**Comment by jenly1314** [comment]
请点击[![Download](https://img.shields.io/badge/download-App-blue.svg)](https://raw.githubusercontent.com/jenly1314/ZXingLite/master/app/release/app-release.apk)下载demo app看是否有问题

**Comment by zcyyouminghuo** [comment]
我也是集成的2.1.0一直崩溃，直接用的captureacitivity

**Comment by zcyyouminghuo** [comment]
startActivityForResult(new Intent(context,CaptureActivity.class),requestCode);后一直直接崩溃

**Comment by 330676687** [comment]
我也是，从2.0.3更新到2.1.0就崩溃，
CameraX is not configured properly. The most likely cause is you did not include a default implementation in your build such as 'camera-camera2'.

**Comment by jenly1314** [comment]
出现此问题一般可能是同时引入的其它第三方库也有依赖 **CamreraX** 相关，与**ZXingLite**使用的**CameraX**版本不一致，主要原因是 **CameraX** 不同版本之间可能不完全兼容导致。**ZXingLite 2.1.0**  版本使用 **CameraX** 的版本是**1.0.0**，你可以试着排除掉其它第三方库依赖的 **CameraX** 相关，或强制指定**CameraX**版本为 **1.0.0**。

**Comment by zcyyouminghuo** [comment]
好的。谢谢，我在研究研究




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jenly1314/ZXingLite"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月21日(星期三) 上午10:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jenly1314/ZXingLite] 2.1.0集成一直崩溃，CameraX is not configured properly (#149)





 
出现此问题一般可能是同时引入的其它第三方库也有依赖 CamreraX 相关，与ZXingLite使用的CameraX版本不一致，主要原因是 CameraX 不同版本之间可能不完全兼容导致。ZXingLite 2.1.0  版本使用 CameraX 的版本是1.0.0，你可以试着排除掉其它第三方库依赖的 CameraX 相关，或强制指定CameraX版本为 1.0.0。

**Comment by daleiyinsi** [comment]
我也一直崩溃，没法解决

**Comment by jenly1314** [comment]
> 我也一直崩溃，没法解决

上面的回答应该已经很详细，请确保最终使用的 **CameraX** 版本为 1.0.0

**Comment by SmallSevenFromCN** [comment]
configurations.all {
        resolutionStrategy.force 'androidx.camera:camera-core:1.0.1'
        resolutionStrategy.force 'androidx.camera:camera-camera2:1.0.1'
        resolutionStrategy.force 'androidx.camera:camera-lifecycle:1.0.1'
        resolutionStrategy.force 'androidx.camera:camera-view:1.0.0-alpha27'
    }

**Comment by isnoam** [comment]
有没有已经解决了的  麻烦说说哪里问题
