### ISSUE TITLE
扫码界面预览只预览了一半的画面

### ISSUE THREAD

**Issue by JIanyag** [jenly1314/ZXingLite#152]
把Demo里的代码复制到项目中，包括布局，都检查过了，相机预览还是变形，变成界面上半部分显示，下半部分黑屏
求解。还是没找到怎么会这样的问题
PS:Demo是正常的。

**Comment by jenly1314** [comment]
demo正常，那应该是你布局问题

**Comment by Brook688** [comment]
我也遇到了，就很尴尬😅

**Comment by Brook688** [comment]
找到原因了，是在AndroidManifest里面把android:hardwareAccelerated="false" 设置false，硬件加速关了，就会出现这种情况。
