### ISSUE TITLE
你好，识别本地图片传入的bitmappath是什么

### ISSUE THREAD

**Issue by bufanx** [jenly1314/ZXingLite#153]
你好，识别本地图片传入的bitmappath是什么，你传的是bitmap,我需要传一个string类型

**Comment by jenly1314** [comment]
识别支持传 **Bitmap** 对象或者 **Bitmap** 的路径，不知道你指的string是 **Bitmap的路径** 还是**Bitmap的字节转Base64后的字符串**。
