### ISSUE TITLE
2.0.2以上部分手机无法扫码

### ISSUE THREAD

**Issue by smallgirl** [jenly1314/ZXingLite#155]
有两个手机
一个一加、一个联想
2.0.2 两个手机所有二维码都可以扫
2.0.3 或者 2.1.0 一加所有二维码都可以扫, 联想所有二维码都扫不出来, 用 google zxing gogle play上的apk 测试都可以扫.另外下载的 releas.apk 也无法扫出来

**Comment by smallgirl** [comment]
ImageAnalysis imageAnalysis = mCameraConfig.options(new ImageAnalysis.Builder()
                        .setTargetResolution(mTargetSize)
                        .setBackpressureStrategy(ImageAnalysis.STRATEGY_KEEP_ONLY_LATEST));

 注释掉    .setTargetResolution(mTargetSize)  就可以了 targetSize算出来比屏幕宽高还大

D/ZXingLite|DefaultCameraScan.initData(DefaultCameraScan.java:158): displayMetrics:800x1216
D/ZXingLite|DefaultCameraScan.initData(DefaultCameraScan.java:175): targetSize:800x1408

**Comment by jenly1314** [comment]
#142

**Comment by smallgirl** [comment]
2.0.2版本 没有TargetResolution或者 2.1.0版本 注释掉TargetResolution 部分手机也是一直扫码不出结果(用户手机、暂时无法看到日志).换成google 的zxing不做修改,用户测试可以扫出来.

**Comment by smallgirl** [comment]
但是用户手机  从相册直接识图片别二维码是可以的.
