### ISSUE TITLE
Android10 CodeUtils.parseCode崩溃

### ISSUE THREAD

**Issue by Mdany** [jenly1314/ZXingLite#157]
未兼容Android10，Manifest需要自己添加requestLegacyExternalStorage=true

建议项目添加或者兼容Android10

**Comment by xxd6772123** [comment]
请问还有其他解决方式吗？发现无法扫描

**Comment by jenly1314** [comment]
用法问题，请使用`CodeUtils.parseCode(Bitmap bitmap)`  替代  `CodeUtils.parseCode(String bitmapPath)`

**Comment by sorrybeman** [comment]
要用返回的Uri获取一个Bitmap
