### ISSUE TITLE
增加mavenCentral()配置

### ISSUE THREAD

**Issue by Mdany** [jenly1314/ZXingLite#163]
jcenter不时会报错，请增加mavenCentral()替代

**Comment by jenly1314** [comment]
看下 **README** 有相关说明， **2.1.0** 以前版本发布至 **JCenter** ，**2.1.0** 版本开始就是发布至 **mavenCentral**。不知你说的jcenter不时会报错具体是什么意思？

**Comment by Mdany** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':cordova-lib:generateDebugRFile'.
> Could not resolve all task dependencies for configuration ':cordova-lib:debugCompileClasspath'.
   > Could not resolve androidx.camera:camera-core:[1.0.0-rc05].
     Required by:
         project :cordova-lib > androidx.camera:camera-view:1.0.0-alpha27
      > Failed to list versions for androidx.camera:camera-core.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/androidx/camera/camera-core/maven-metadata.xml.
            > Could not get resource 'https://jcenter.bintray.com/androidx/camera/camera-core/maven-metadata.xml'.
               > Could not GET 'https://jcenter.bintray.com/androidx/camera/camera-core/maven-metadata.xml'.
                  > Remote host terminated the handshake

是ZXingLite项目代码里没有用mavenCentral

**Comment by jenly1314** [comment]
**camera-core** 这个库在 **google()** 仓库中能找到的，应该是网络访问google的maven仓库不稳定导致的。在通过gradle拉取远程仓库依赖时，会通过遍历配置的仓库地址中一个个去拉取所需的依赖，当在遍历完所配置的仓库地址中依旧没有找到所需依赖时，才会抛出异常。
