### ISSUE TITLE
扫码识别框，通过padding产生偏移后，真实的识别区域并没有改变，导致扫码识别框偏移出去的部分并不能识别二维码

### ISSUE THREAD

**Issue by windfallsheng** [jenly1314/ZXingLite#165]
扫码识别框，通过padding产生偏移后，真实的识别区域并没有改变，导致扫码识别框偏移出去的部分并不能识别二维码

**Comment by jenly1314** [comment]
看下 **README** 中的说明 或 看下 [API帮助文档](https://jenly1314.github.io/projects/ZXingLite/doc/) 中 `DecodeConfig.setAreaRectVerticalOffset(int areaRectVerticalOffset);` 相关的说明
