### ISSUE TITLE
【建议】更改扫描回调方式，activityResult 已经废弃了。

### ISSUE THREAD

**Issue by zqlq4ever** [jenly1314/ZXingLite#169]

**Comment by jenly1314** [comment]
只是调用和回调的方式改了，返回方式没有变，所以并不影响 **ZXingLite** 的使用。
至于使用旧的 **startActivityForResult**，**onActivityResult** 方式，还是使用新的 **registerForActivityResult** 方式在于你的选择。
我只需抽空改下相关示例即可。

**Comment by zqlq4ever** [comment]
原来如此，谢谢解答。
