### ISSUE TITLE
下载源码编译识别速度很慢

### ISSUE THREAD

**Issue by walker113** [jenly1314/ZXingLite#17]
下载源码重新编译扫码二维码识别很慢， 但自己用提供的apk识别则很快，什么原因呢？

**Comment by jenly1314** [comment]
源码会不定期维护更新，不建议直接使用源码编译，推荐使用gradle引入方式。ZXxingLite本身支持扫码界面自定义，满足基本使用。如果有什么不满足需求的或者有什么好的建议可以提出。
