### ISSUE TITLE
从相册选择照片识别时，部分二维码无法识别，直接扫码识别是支持的

### ISSUE THREAD

**Issue by mry1** [jenly1314/ZXingLite#170]
<img width="251" alt="企业微信20211106-154354@2x" src="https://user-images.githubusercontent.com/18238088/140602174-99c5357f-ac37-4e80-99c3-a086d1060d03.png">

从相册选择这张二维码无法识别

**Comment by liukai-2p** [comment]
解决了吗

**Comment by jenly1314** [comment]
#69
