### ISSUE TITLE
小米平板平行窗口适配

### ISSUE THREAD

**Issue by fywalll** [jenly1314/ZXingLite#176]
[](url)小米和华为平板中,开启了平行窗口的话没有很好的适配
 步骤:横屏模式下,打开了平行窗口,开启了扫码页
1.摄像头方向错误
2.拖动扫码页宽度的时候,扫描框大小没变

**Comment by Allen8Lee** [comment]
您发送的邮件我已收到。

**Comment by fywalll** [comment]
![Screenshot_2021-12-08-10-02-45-901_com king zxing app](https://user-images.githubusercontent.com/70688342/145136042-3c1b72e2-1c9e-4242-83a3-4ee375753c9c.jpg)

**Comment by jenly1314** [comment]
> ![Screenshot_2021-12-08-10-02-45-901_com king zxing app](https://user-images.githubusercontent.com/70688342/145136042-3c1b72e2-1c9e-4242-83a3-4ee375753c9c.jpg)

不分屏并且在开启自动旋转的情况下，麻烦用平板测下demo中的app，通过重力感应切换横竖屏，看下摄像头方向是否正确。

**Comment by fywalll** [comment]
不分屏的情况下摄像头正常

**Comment by jenly1314** [comment]
我用手机测了下，分屏时旋转屏幕摄像头是正常的；不太好定位平板上分屏时出现的这个问题。
你可以加些日志，看下分屏时旋转屏幕，打印下屏幕方向和旋转角度相关信息；或者也可以通过 **CameraConfig** 设置摄像头相关配置。
