### ISSUE TITLE
偶现  java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by Mocaris** [jenly1314/ZXingLite#177]
# main(1)
java.lang.OutOfMemoryError
Failed to allocate a 1000012 byte allocation with 334096 free bytes and 326KB until OOM
1
com.king.zxing.util.CodeUtils.createQRCode(CodeUtils.java:166)
2
com.king.zxing.util.CodeUtils.createQRCode(CodeUtils.java:144)
3
com.king.zxing.util.CodeUtils.createQRCode(CodeUtils.java:105)
4
com.king.zxing.util.CodeUtils.createQRCode(CodeUtils.java:82)

**Comment by jenly1314** [comment]
两种解决方式：
1. 生成二维码时 **bitmap** 不要太大（包括二维码中间的logo图片）
2. 在 **manifest** 的 **application** 配置中加上 `android:largeHeap="true"` ，来申请更大的内存

**Comment by Mocaris** [comment]
> 两种解决方式：
> 
> 1. 生成二维码时 **bitmap** 不要太大（包括二维码中间的logo图片）
> 2. 在 **manifest** 的 **application** 配置中加上 `android:largeHeap="true"` ，来申请更大的内存

生成的bitmap 并没有很大，只给了500px 的大小,也没有添加logo
