### ISSUE TITLE
小米mix2s Android9无法识别

### ISSUE THREAD

**Issue by a124609322** [jenly1314/ZXingLite#18]
小米mix2s Android9无法识别。没任何反应呢

**Comment by guoai2015** [comment]
同款机器同问，demo里打开任何一个扫码界面都扫码无反应，扫码不出二维码。但是从相册里选二维码图片可以扫码出来。

**Comment by jinsen1** [comment]
这边也发现一个 小米mix2 也是识别特别慢，偶尔可以识别
