### ISSUE TITLE
 duplicate value for resource 'attr/scaleType' with config ''.

### ISSUE THREAD

**Issue by kimiangel** [jenly1314/ZXingLite#180]
duplicate value for resource 'attr/scaleType' with config ''.怎么处理这种

**Comment by Allen8Lee** [comment]
您发送的邮件我已收到。

**Comment by jenly1314** [comment]
> duplicate value for resource 'attr/scaleType' with config ''.怎么处理这种

1. 自定义属性 **scaleType** 重复了，全局搜下修改其中一个即可；
2. 这个跟 **ZXingLite** 没什么关系吧，ZXingLite中并没有定义 **scaleType** ；应该是其他第三方库中的自定义属性。

**Comment by DevDengChao** [comment]
```
> Task :app:mergeDebugResources FAILED
D:\users\admin\.gradle\caches\transforms-3\xxx\transformed\jetified-pictureselector-v2.7.3-rc02\res\values\values.xml:414:4:
 Duplicate value for resource 'attr/scaleType' with config 'DEFAULT' and product ''. 
Resource was previously defined here: D:\users\admin\.gradle\caches\transforms-3\xxx\transformed\jetified-camera-view-1.0.0-alpha27\res\values\values.xml:6:4: .
```

```
+--- io.github.lucksiege:pictureselector:v2.7.3-rc02                                      // outdated
|    +--- androidx.appcompat:appcompat:1.3.0 -> 1.4.1 (*)
|    +--- androidx.recyclerview:recyclerview:1.2.0 -> 1.2.1 (*)
|    +--- androidx.concurrent:concurrent-futures:1.1.0
|    |    +--- androidx.annotation:annotation:1.1.0 -> 1.3.0
|    |    \--- com.google.guava:listenablefuture:1.0
|    +--- androidx.annotation:annotation-experimental:1.1.0
|    +--- com.squareup.okio:okio:3.0.0-alpha.4 (*)
|    +--- androidx.exifinterface:exifinterface:1.3.2 (*)
|    +--- androidx.localbroadcastmanager:localbroadcastmanager:1.0.0 (*)
|    +--- androidx.camera:camera-view:1.0.0-alpha24 -> 1.0.0-alpha27         // possible reason
|    |    +--- androidx.lifecycle:lifecycle-common:2.0.0 -> 2.4.0 (*)
|    |    +--- androidx.annotation:annotation:1.2.0 -> 1.3.0
|    |    \--- androidx.camera:camera-core:1.0.0-rc05 -> 1.1.0-alpha04
|    |         +--- androidx.annotation:annotation:1.0.0 -> 1.3.0
|    |         +--- androidx.lifecycle:lifecycle-livedata:2.1.0 (*)
|    |         +--- com.google.guava:listenablefuture:1.0
|    |         +--- androidx.annotation:annotation-experimental:1.1.0-rc01 -> 1.1.0
|    |         \--- org.jetbrains.kotlin:kotlin-stdlib:1.4.32 -> 1.5.31 (*)
|    +--- androidx.transition:transition:1.4.1 (*)
|    \--- androidx.camera:camera-lifecycle:1.1.0-alpha04
|         +--- androidx.lifecycle:lifecycle-common:2.1.0 -> 2.4.0 (*)
|         +--- com.google.guava:listenablefuture:1.0
|         \--- androidx.camera:camera-core:1.1.0-alpha04 (*)
|
\--- com.github.jenly1314:zxing-lite:2.1.1
     +--- com.google.zxing:core:3.3.3
     +--- androidx.camera:camera-core:1.0.1 -> 1.1.0-alpha04 (*)
     +--- androidx.camera:camera-camera2:1.0.1
     |    +--- androidx.camera:camera-core:1.0.1 -> 1.1.0-alpha04 (*)
     |    +--- androidx.annotation:annotation:1.0.0 -> 1.3.0
     |    +--- androidx.annotation:annotation-experimental:1.0.0 -> 1.1.0
     |    +--- androidx.core:core:1.1.0 -> 1.7.0 (*)
     |    +--- androidx.concurrent:concurrent-futures:1.0.0 -> 1.1.0 (*)
     |    +--- com.google.guava:listenablefuture:1.0
     |    \--- com.google.auto.value:auto-value-annotations:1.6.3
     +--- androidx.camera:camera-lifecycle:1.0.1 -> 1.1.0-alpha04 (*)
     \--- androidx.camera:camera-view:1.0.0-alpha27 (*)                              
```

我在升级 `zxing-lite` 的时候也遇到了这个问题，查了一下 `app` 模块的依赖关系， 发现 `io.github.lucksiege:pictureselector:v2.7.3-rc02` 依赖的 `camera-view` 出现了依赖升级，尝试性的更新 `pictureselector` 后恢复正常，可以编译了。

**Comment by Allen8Lee** [comment]
您发送的邮件我已收到。

**Comment by jenly1314** [comment]
> ```
> > Task :app:mergeDebugResources FAILED
> D:\users\admin\.gradle\caches\transforms-3\xxx\transformed\jetified-pictureselector-v2.7.3-rc02\res\values\values.xml:414:4:
>  Duplicate value for resource 'attr/scaleType' with config 'DEFAULT' and product ''. 
> Resource was previously defined here: D:\users\admin\.gradle\caches\transforms-3\xxx\transformed\jetified-camera-view-1.0.0-alpha27\res\values\values.xml:6:4: .
> ```
> 
> ```
> +--- io.github.lucksiege:pictureselector:v2.7.3-rc02                                      // outdated
> |    +--- androidx.appcompat:appcompat:1.3.0 -> 1.4.1 (*)
> |    +--- androidx.recyclerview:recyclerview:1.2.0 -> 1.2.1 (*)
> |    +--- androidx.concurrent:concurrent-futures:1.1.0
> |    |    +--- androidx.annotation:annotation:1.1.0 -> 1.3.0
> |    |    \--- com.google.guava:listenablefuture:1.0
> |    +--- androidx.annotation:annotation-experimental:1.1.0
> |    +--- com.squareup.okio:okio:3.0.0-alpha.4 (*)
> |    +--- androidx.exifinterface:exifinterface:1.3.2 (*)
> |    +--- androidx.localbroadcastmanager:localbroadcastmanager:1.0.0 (*)
> |    +--- androidx.camera:camera-view:1.0.0-alpha24 -> 1.0.0-alpha27         // possible reason
> |    |    +--- androidx.lifecycle:lifecycle-common:2.0.0 -> 2.4.0 (*)
> |    |    +--- androidx.annotation:annotation:1.2.0 -> 1.3.0
> |    |    \--- androidx.camera:camera-core:1.0.0-rc05 -> 1.1.0-alpha04
> |    |         +--- androidx.annotation:annotation:1.0.0 -> 1.3.0
> |    |         +--- androidx.lifecycle:lifecycle-livedata:2.1.0 (*)
> |    |         +--- com.google.guava:listenablefuture:1.0
> |    |         +--- androidx.annotation:annotation-experimental:1.1.0-rc01 -> 1.1.0
> |    |         \--- org.jetbrains.kotlin:kotlin-stdlib:1.4.32 -> 1.5.31 (*)
> |    +--- androidx.transition:transition:1.4.1 (*)
> |    \--- androidx.camera:camera-lifecycle:1.1.0-alpha04
> |         +--- androidx.lifecycle:lifecycle-common:2.1.0 -> 2.4.0 (*)
> |         +--- com.google.guava:listenablefuture:1.0
> |         \--- androidx.camera:camera-core:1.1.0-alpha04 (*)
> |
> \--- com.github.jenly1314:zxing-lite:2.1.1
>      +--- com.google.zxing:core:3.3.3
>      +--- androidx.camera:camera-core:1.0.1 -> 1.1.0-alpha04 (*)
>      +--- androidx.camera:camera-camera2:1.0.1
>      |    +--- androidx.camera:camera-core:1.0.1 -> 1.1.0-alpha04 (*)
>      |    +--- androidx.annotation:annotation:1.0.0 -> 1.3.0
>      |    +--- androidx.annotation:annotation-experimental:1.0.0 -> 1.1.0
>      |    +--- androidx.core:core:1.1.0 -> 1.7.0 (*)
>      |    +--- androidx.concurrent:concurrent-futures:1.0.0 -> 1.1.0 (*)
>      |    +--- com.google.guava:listenablefuture:1.0
>      |    \--- com.google.auto.value:auto-value-annotations:1.6.3
>      +--- androidx.camera:camera-lifecycle:1.0.1 -> 1.1.0-alpha04 (*)
>      \--- androidx.camera:camera-view:1.0.0-alpha27 (*)                              
> ```
> 
> 我在升级 `zxing-lite` 的时候也遇到了这个问题，查了一下 `app` 模块的依赖关系， 发现 `io.github.lucksiege:pictureselector:v2.7.3-rc02` 依赖的 `camera-view` 出现了依赖升级，尝试性的更新 `pictureselector` 后恢复正常，可以编译了。

依赖的 **camera-view** 是google官方的库，这个冲突问题应该让 **pictureselector** 的作者去配合修改。

**Comment by DevDengChao** [comment]
建议 `zxing-lite` 依赖稳定版的第三方/官方库, 避免引发此类由于依赖了 alpha 版/预览版库的问题.
或者更进一步的, `zxing-lite` 也使用类似的机制, 在稳定版外单独开设预览版.

**Comment by jenly1314** [comment]
> 建议 `zxing-lite` 依赖稳定版的第三方/官方库, 避免引发此类由于依赖了 alpha 版/预览版库的问题. 或者更进一步的, `zxing-lite` 也使用类似的机制, 在稳定版外单独开设预览版.

我也想用，只是google官方目前一直没有发布 **camera-view** 稳定的版本。
