### ISSUE TITLE
HONOR X30 MagicUI 版本 5.0   扫描二维码报错

### ISSUE THREAD

**Issue by clg0118** [jenly1314/ZXingLite#186]
HONOR X30 MagicUI 版本 5.0 
扫描二维码 ：
result = mReader.decodeWithState(new BinaryBitmap(new HybridBinarizer(source)));
报 com.google.zxing.NotFoundException 错误

**Comment by jenly1314** [comment]
> HONOR X30 MagicUI 版本 5.0 扫描二维码 ： result = mReader.decodeWithState(new BinaryBitmap(new HybridBinarizer(source))); 报 com.google.zxing.NotFoundException 错误

识别失败，捕捉了异常，这个异常不是很合理么？

**Comment by clg0118** [comment]
大部分手机扫描都没有问题，也都不报错，目前发现只有 HONOR X30 MagicUI 版本 5.0  、OPPO A93 colorOS V11.1 这两个手机扫描报错，用的2.1.1版本的

**Comment by Jiekkx** [comment]
同荣耀X30手机，扫描无法识别二维码。手里其它型号的手机都可以。希望大神有时间查一下原因。

**Comment by jenly1314** [comment]
[#181](https://github.com/jenly1314/ZXingLite/issues/181#issuecomment-1510054289)
