### ISSUE TITLE
怎么设置只识别条形码？

### ISSUE THREAD

**Issue by zenghaixiao** [jenly1314/ZXingLite#187]
请问怎么设置只识别条形码？

**Comment by jenly1314** [comment]
请查看 **DecodeConfig** 相关配置

示例代码
```
       //初始化解码配置
        DecodeConfig decodeConfig = new DecodeConfig();
        decodeConfig.setHints(DecodeFormatManager.QR_CODE_HINTS);//如果只有识别二维码的需求，这样设置效率会更高

        //在启动预览之前，设置分析器，只识别二维码
        getCameraScan()
                .setAnalyzer(new MultiFormatAnalyzer(decodeConfig));
```

**Comment by zenghaixiao** [comment]
你这个是识别二维码的，我只想识别条形码



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月25日(周五) 下午5:42
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jenly1314/ZXingLite] 怎么设置只识别条形码？ (Issue #187)




 
请查看 DecodeConfig 相关配置
 
示例代码
        //初始化解码配置         DecodeConfig decodeConfig = new DecodeConfig();         decodeConfig.setHints(DecodeFormatManager.QR_CODE_HINTS);//如果只有识别二维码的需求，这样设置效率会更高         //在启动预览之前，设置分析器，只识别二维码         getCameraScan()                 .setAnalyzer(new MultiFormatAnalyzer(decodeConfig));

**Comment by wmgm183** [comment]
同求，我也想知道，用来扫描商品条码的，方便出库入库

**Comment by jenly1314** [comment]
> 同求，我也想知道，用来扫描商品条码的，方便出库入库

上面的回答示例已经很清楚的说明了解码配置相关的用法，要学会举一反三，至于你的需求是需要识别一维码还是二维码，麻烦稍微动动手，到 **DecodeFormatManager** 类中稍微看一下，根据你自己的需求去决定要识别哪种类型的码。

**Comment by wmgm183** [comment]
初学安卓，连java都是半桶水，要是知道 就不提问了

**Comment by wmgm183** [comment]
> > 同求，我也想知道，用来扫描商品条码的，方便出库入库
> 
> 上面的回答示例已经很清楚的说明了解码配置相关的用法，要学会举一反三，至于你的需求是需要识别一维码还是二维码，麻烦稍微动动手，到 **DecodeFormatManager** 类中稍微看一下，根据你自己的需求去决定要识别哪种类型的码。

CODE_128_HINTS  ONE_DIMENSIONAL_HINTS  好像只识别一维码，但是相机还是那个二维码相机，是要在布局里面自己改相机高度吗
