### ISSUE TITLE
请问这种变形二维码怎么识别？

### ISSUE THREAD

**Issue by WaSuper** [jenly1314/ZXingLite#189]
![code](https://user-images.githubusercontent.com/13520244/160395749-7b85ca57-b584-44b2-8cbf-1561895eee34.png)
大佬，用这个库对这种码扫描没有反应，这是微信自己设计的二维码吗？微信扫一扫可以显示我们地区的健康码的。
后续会有更新增加这个功能吗？
或者有推荐哪种库可以识别？

**Comment by jenly1314** [comment]
> ![code](https://user-images.githubusercontent.com/13520244/160395749-7b85ca57-b584-44b2-8cbf-1561895eee34.png) 大佬，用这个库对这种码扫描没有反应，这是微信自己设计的二维码吗？微信扫一扫可以显示我们地区的健康码的。 后续会有更新增加这个功能吗？ 或者有推荐哪种库可以识别？

好家伙，竟然直接贴粤康码，这种小程序码只是借鉴了二维码的思想，重新定义了一套规则；其中一个主要作用就是提高安全性；目前应该只有微信能扫，因为小程序码是微信定义的一套编解码规则。记得之前看过一篇这种异形二维码相关介绍的文章，类似于小程序码的这种异形二维码，国外也有类似的，都只是借鉴二维码的思想，然后自定义一套规则。
