### ISSUE TITLE
能支持前置摄像头么

### ISSUE THREAD

**Issue by amusiaHzr** [jenly1314/ZXingLite#19]
RT

**Comment by jenly1314** [comment]
自己调用camera.open(int cameraId);   很好奇是什么场景、前置一般用来自拍、脸上有二维码、？

**Comment by hxmeie** [comment]
哈哈，我也在想脸上有二维码吗

**Comment by amusiaHzr** [comment]
调用了cameraManager.setManualCameraId(Camera.CameraInfo.CAMERA_FACING_FRONT)，前置摄像头预览画面能出来，但是扫描不出来。

**Comment by amusiaHzr** [comment]
前置能扫出来，不能扫出来的是另外一个项目，我弄混了，尴尬.jpg
