### ISSUE TITLE
识别不太清楚的二维码多试几次 界面卡死。demo 也复现了 

### ISSUE THREAD

**Issue by tangweihong** [jenly1314/ZXingLite#193]
相册选择图片识别不太清楚的二维码返回空数据， 多识别几次 页面卡死黑屏一段时间。 用demo 测试 也复现了。 
![微信图片_20220516190111](https://user-images.githubusercontent.com/9458645/168579605-a090f80c-bf52-47e4-802b-a40b00622850.jpg)

**Comment by 549064368** [comment]
解决了吗

**Comment by flute00** [comment]
解决了吗

**Comment by ikimiler** [comment]
准确的说识别一个非二维码图片，程序直接卡死

**Comment by Allen8Lee** [comment]
您发送的邮件我已收到。

**Comment by jenly1314** [comment]
#69
