### ISSUE TITLE
frameHeight高度不生效

### ISSUE THREAD

**Issue by pengjunshan** [jenly1314/ZXingLite#194]
设置**frameHeight**高度不生效

**Comment by Allen8Lee** [comment]
您发送的邮件我已收到。

**Comment by pengjunshan** [comment]
if(initFrameHeight <= 0 || initFrameHeight > height){
            frameHeight = size;
        }else {
            frameHeight = initFrameHeight;
        }
加上else代码就好了

**Comment by jenly1314** [comment]
> ```
>     if(initFrameHeight <= 0 || initFrameHeight > height){
>         frameHeight = size;
>     }else {
>         frameHeight = initFrameHeight;
>     }
> ```
> 
> 加上else代码就好了

看了下git提交记录，你可以按你这么改，也可以使用 **v2.1.1** 版本，这是 **v2.2.0** 版本改动出的bug，后续版本将修复此bug。

**Comment by Allen8Lee** [comment]
您发送的邮件我已收到。
