### ISSUE TITLE
labelTextWidth 属性冲突，用的2.2.1的版本，现在退回到2.0.1使用了

### ISSUE THREAD

**Issue by jiangsai** [jenly1314/ZXingLite#195]
![image](https://user-images.githubusercontent.com/19963883/176841386-236a867e-8dcb-4287-92ae-2e24a9adccb3.png)
![image](https://user-images.githubusercontent.com/19963883/176841491-7f23d2ef-1bc5-4505-aeda-82e4cdb391b3.png)

**Comment by jenly1314** [comment]
#### 这种自定义属性冲突问题，一般是项目中引入了两个第三方库，使用了相同的自定义属性导致。

当你遇到时这种自定义属性冲突时，如果你确实两个库都需要引入，则需修改一下其中一个库的自定义属性名称即可。（如：将其中一个库中定义的 **labelTextWidth** 改成其它名称）
#### 下面有两种修改方式：
1. 可以改变其中一个库的依赖方式，以 **library** 的方式引入，然后修改自定义属性名称。
2. 看哪个库的代码相对简单一点，将其拷贝到你项目中中，然后修改自定义属性名称。

**Comment by jiangsai** [comment]
这个属性都是2.0.1以上版本库里面依赖别的库导致的，并不是自己项目中有这个属性导致的。作者可以自己试试
