### ISSUE TITLE
比较复杂的二维码，多扫几次会有扫出数字的问题，图中扫了三次，两次是正常的

### ISSUE THREAD

**Issue by jiangsai** [jenly1314/ZXingLite#196]
![image](https://user-images.githubusercontent.com/19963883/176845200-7e81f44b-a099-4b91-b98c-f25feeb06c11.png)
![image](https://user-images.githubusercontent.com/19963883/176845250-f28beb75-c140-4933-acdf-cc54a5ef80db.png)

**Comment by jiangsai** [comment]
demo也会出现这个问题

**Comment by jenly1314** [comment]
这种是 **zxing** 本身的问题；不过你可以通过配置扫码支持 **识别的条形码/二维码** 来降低这种问题的出现概率。

比如只有识别二维码的需求时，可以参照下面的配置：
```
        //初始化解码配置
        DecodeConfig decodeConfig = new DecodeConfig();
        decodeConfig.setHints(DecodeFormatManager.QR_CODE_HINTS)//如果只有识别二维码的需求，这样设置效率会更高，不设置默认为DecodeFormatManager.DEFAULT_HINTS

        //在启动预览之前，设置分析器，只识别二维码
        getCameraScan()
                .setAnalyzer(new MultiFormatAnalyzer(decodeConfig));//设置分析器,如果内置实现的一些分析器不满足您的需求，你也可以自定义去实现
```
