### ISSUE TITLE
图形预览变形

### ISSUE THREAD

**Issue by Theoneee** [jenly1314/ZXingLite#2]
机型： 魅族 15  android 7.1.1   
![qq 20180816165012](https://user-images.githubusercontent.com/32156330/44198629-80900300-a174-11e8-8f60-211f65986ef0.jpg)

**Comment by YanYanLun** [comment]
这个是zxing的问题

**Comment by YanYanLun** [comment]
已经测试，同样的问题，希望解决下

**Comment by DuShuYuan** [comment]
同问题
