### ISSUE TITLE
有考虑出个 zbar 结合版吗？

### ISSUE THREAD

**Issue by ZQ173** [jenly1314/ZXingLite#203]
如题，zbar 扫码速度较快，zxing 识别率较高但是慢，结合一下先 zbar 再 zing 可好？

**Comment by jenly1314** [comment]
> 如题，zbar 扫码速度较快，zxing 识别率较高但是慢，结合一下先 zbar 再 zing 可好？

可以试试用 [MLKit](https://github.com/jenly1314/MLKit) 或 [WeChatQRCode](https://github.com/jenly1314/WeChatQRCode)
