### ISSUE TITLE
有空指针报错

### ISSUE THREAD

**Issue by 1825492258** [jenly1314/ZXingLite#209]
我用的版本是com.github.jenly1314:zxing-lite:2.1.0
在Android10，的HuaWei/EMOTION上存在空指针报错
Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
com.king.zxing.util.CodeUtils.getRGBLuminanceSource(CodeUtils.java:468)
Bugly里面的反馈
java.lang.RuntimeException:Failure delivering result ResultInfo{who=null, request=10002, result=-1, data=Intent { flg=0x1 hwFlg=0x10 (has extras) }} to activity {cn.linkintec.smarthouse/com.rs.ui.dev.add.zxing.ZXingCodeActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference

刚想升级到2.3.0然后我用compileSdkVersion是30，编译不过，提示The minCompileSdk (33) specified in 这个必须要我升级到32才能处理吗？

**Comment by Allen8Lee** [comment]
您发送的邮件我已收到。

**Comment by jenly1314** [comment]
> 我用的版本是com.github.jenly1314:zxing-lite:2.1.0 在Android10，的HuaWei/EMOTION上存在空指针报错 Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference com.king.zxing.util.CodeUtils.getRGBLuminanceSource(CodeUtils.java:468) Bugly里面的反馈 java.lang.RuntimeException:Failure delivering result ResultInfo{who=null, request=10002, result=-1, data=Intent { flg=0x1 hwFlg=0x10 (has extras) }} to activity {cn.linkintec.smarthouse/com.rs.ui.dev.add.zxing.ZXingCodeActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
> 
> 刚想升级到2.3.0然后我用compileSdkVersion是30，编译不过，提示The minCompileSdk (33) specified in 这个必须要我升级到32才能处理吗？

* 你这报错很明显，bitmap为空导致；请检查下你获取bitmap的相关代码。
* **README** 的 **温馨提示** 部分有compileSdkVersion 要求相关说明

**Comment by 1825492258** [comment]
OK
