### ISSUE TITLE
希望可以给出一个apk的下载链接，想看看demo效果。这个库，clone的时候不知道为什么很慢

### ISSUE THREAD

**Issue by StriveCheng** [jenly1314/ZXingLite#21]

**Comment by jenly1314** [comment]
[![Download](https://img.shields.io/badge/download-App-blue.svg)](https://raw.githubusercontent.com/jenly1314/ZXingLite/master/app/release/app-release.apk)ase.apk)

**Comment by StriveCheng** [comment]
感谢感谢
