### ISSUE TITLE
怎么能设置扫码框内的背景

### ISSUE THREAD

**Issue by Demonhuang** [jenly1314/ZXingLite#210]
如题 想设置扫码框内的遮罩 和扫码框外的 也就是设置maskColor的一样的颜色 如何设置 感谢回答

**Comment by jenly1314** [comment]
框外的遮罩，可直接通过布局配置，示例如下：
```xml
<com.king.zxing.ViewfinderView
        android:id="@+id/viewfinderView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:maskColor="@color/viewfinder_mask"/>
```
可参考：[布局示例](https://github.com/jenly1314/ZXingLite/blob/master/app/src/main/res/layout/custom_capture_activity.xml)

框内遮罩是什么意思，不太理解你的意图。页面布局全部遮罩（布局遮一层）或者全部不遮罩（maskColor设置为透明）？

**Comment by Demonhuang** [comment]
<img width="255" alt="image" src="https://user-images.githubusercontent.com/11385157/224877322-7cedfed0-c71b-4180-955b-d0a302be20d0.png">
扫描框内颜色是透明的 现在是想要效果这样跟maskColor设置同样颜色

**Comment by jenly1314** [comment]
在前面的一次回复中，我好像已经给出了相应的解决方案。（maskColor设置为透明，然后布局遮一层。）

**Comment by Demonhuang** [comment]
还有个问题我想请教下 就是扫描线我们的 会超过扫描框 我看咱们的是在框画的 这个有方法改变么 感谢回答
