### ISSUE TITLE
onScanResultCallback return false (app closes)

### ISSUE THREAD

**Issue by Agmcz** [jenly1314/ZXingLite#212]
I'm trying to qr scan single, but app closes!!!

mCameraScan.setOnScanResultCallback(new CameraScan.OnScanResultCallback() {
    @Override
    public boolean onScanResultCallback(Result result) {
        // some code
        return false;
      }
});

**Comment by jenly1314** [comment]
> I'm trying to qr scan single, but app closes!!!
> 
> mCameraScan.setOnScanResultCallback(new CameraScan.OnScanResultCallback() { @OverRide public boolean onScanResultCallback(Result result) { // some code return false; } });

If you need to process the scan callback result, please intercept the callback and return true. 

See [OnScanResultCallback ](https://github.com/jenly1314/ZXingLite/blob/master/zxing-lite/src/main/java/com/king/zxing/CameraScan.java#L182) and [scanResultCallback](https://github.com/jenly1314/ZXingLite/blob/master/zxing-lite/src/main/java/com/king/zxing/DefaultCameraScan.java#L359) for details.

See [CustomCaptureActivity](https://github.com/jenly1314/ZXingLite/blob/master/app/src/main/java/com/king/zxing/app/CustomCaptureActivity.java#L116) for sample code.

**Comment by Agmcz** [comment]
Tanck you for this hints, i used the following code to single scan

`// rescanning
isContinuousScan = true;
mCameraScan.setVibrate(true);
mCameraScan.setPlayBeep(true);

mCameraScan.setOnScanResultCallback(new CameraScan.OnScanResultCallback() {
            @Override
            public boolean onScanResultCallback(Result result) {
                if (isContinuousScan) {
                    isContinuousScan = false;
                    mCameraScan.setVibrate(false);
                    mCameraScan.setPlayBeep(false);
                    // some code
                }
                return true;
            }
});`
