### ISSUE TITLE
How to detect black screen

### ISSUE THREAD

**Issue by Agmcz** [jenly1314/ZXingLite#214]
I want to get a screenshot (bitmap) to check the pixels from CameraScan, How can fetch bitmap!!!

**Comment by jenly1314** [comment]
> I want to get a screenshot (bitmap) to check the pixels from CameraScan, How can fetch bitmap!!!

[previewView.getBitmap()](https://github.com/jenly1314/MLKit/blob/master/app/src/main/java/com/king/mlkit/vision/app/barcode/QRCodeScanningActivity.kt#L69) 
Get a bitmap from the preview view. Is this what you need?

**Comment by Agmcz** [comment]
I want to something like this example

                running = true;
                thread = new Thread(new Runnable() {
                    @Override
                    public void run() {
                        while (running) {
                            try {
                                Bitmap bitmap = binding.previewView.getBitmap();

                                int[] histogram = new int[256];
                                // int histogram[256];
                                for (int i=0;i<256;i++) {
                                    histogram[i] = 0;
                                }

                                for (int x = 0; x < bitmap.getWidth(); x++) {
                                    for(int y = 0; y < bitmap.getHeight(); y++) {
                                        int color = bitmap.getPixel(x, y);

                                        int r = Color.red(color);
                                        int g = Color.green(color);
                                        int b = Color.blue(color);

                                        int brightness = (int) (0.2126*r + 0.7152*g + 0.0722*b);
                                        histogram[brightness]++;
                                    }
                                }

                                int allPixelsCount = bitmap.getWidth() * bitmap.getHeight();

                                // Count pixels with brightness less then 10
                                int darkPixelCount = 0;
                                for (int i=0;i<10;i++) {
                                    darkPixelCount += histogram[i];
                                }

                                if (darkPixelCount > allPixelsCount * 0.25) {
                                    // Dark picture. Play with a percentag
                                    // Turn on flash
                                }
                                else {
                                    // Light picture.
                                }
                            } catch (Exception e) {
                                e.printStackTrace();
                            }
                        }
                    }
                });
                thread.start();

**Comment by Agmcz** [comment]
I'm trying to get X,Y of frame (ViewfinderView) to create a small bitmap for fast search...

for example:

Bitmap bitmap = Bitmap.createBitmap(frame.X, frame.X, ...);
if (isDark(bitmap )) {
// trun on flash
} else {
// trun off flash
}

can you help me and thanks adavnced.

**Comment by Agmcz** [comment]
I used "previewView.getBitmap();"

modified "ViewfinderView.java"  (privite Rect frame;) to (public Rect frame;) for using from inside MainActivity...

Bitmap bitmap = Bitmap.createBitmap(binding.previewView.getBitmap(), binding.viewfinderView.frame.left, binding.viewfinderView.frame.top ,binding.viewfinderView.frame.width(), binding.viewfinderView.frame.height());

 but "previewView.getBitmap();" return null!!!

I want to get a bitmap from camerascan and crop bitmap from frame dimensions.

**Comment by jenly1314** [comment]
If obtaining brightness is to switch the flash, it is recommended that you use a sensor to detect changes in brightness.

See: [AmbientLightManager](https://github.com/jenly1314/ZXingLite/blob/master/zxing-lite/src/main/java/com/king/zxing/manager/AmbientLightManager.java)

**Comment by Agmcz** [comment]
Thanks.
