### ISSUE TITLE
Preferred settings for fast scan

### ISSUE THREAD

**Issue by Agmcz** [jenly1314/ZXingLite#215]
What are preferred camerascan settings for fast scan

**Comment by jenly1314** [comment]
> What are preferred camerascan settings for fast scan

There are many default settings for CameraScan. What parameter settings do you mean by the preferred settings for fast scan?

**Comment by Agmcz** [comment]
For example: https://github.com/HappyMiao/QrCodeScan
when i scan same barcodes with QrCodeLib and ZXingLite i notice that QrCodeLib is faster
i asked for a preferred setting to have the scan like QrCodeLib.

**Comment by jenly1314** [comment]
You can refer to the following configuration examples:
```java
        DecodeConfig decodeConfig = new DecodeConfig();
        // The set of hints to use for subsequent calls to decode(image)
        decodeConfig.setHints(DecodeFormatManager.QR_CODE_HINTS);

       // ResolutionCameraConfig or AspectRatioCameraConfig
       cameraScan.setCameraConfig(new ResolutionCameraConfig(this))
                .setAnalyzer(new MultiFormatAnalyzer(decodeConfig));

```

See example: [QRCodeActivity](https://github.com/jenly1314/ZXingLite/blob/master/app/src/main/java/com/king/zxing/app/QRCodeActivity.java)

**Comment by Agmcz** [comment]
Thanks.
