### ISSUE TITLE
识别区域无效

### ISSUE THREAD

**Issue by 1010663814** [jenly1314/ZXingLite#218]
为什么调用了setAnalyzeAreaRect这个方法后，扫码就没用了，哪怕区域设置为(0，0，屏幕宽度，屏幕高度)都不行？

**Comment by jenly1314** [comment]
> 为什么调用了setAnalyzeAreaRect这个方法后，扫码就没用了，哪怕区域设置为(0，0，屏幕宽度，屏幕高度)都不行？

设置识别区域不是这么用的，识别区域是基于分析的图像宽高，而不是屏幕的宽高。更多解释说明可查看方法注释说明或参见：#146
