### ISSUE TITLE
继承 CaptureActivity 崩溃 

### ISSUE THREAD

**Issue by benben1** [jenly1314/ZXingLite#220]
版本：2.4.0
报错：    
1. Caused by: android.view.InflateException: Binary XML file line #9 in com.aliyun.alink.devicesdk.demo:layout/zxl_capture: Binary XML file line #9 in com.aliyun.alink.devicesdk.demo:layout/zxl_capture: Error inflating class androidx.camera.view.PreviewView
2. Caused by: android.view.InflateException: Binary XML file line #9 in com.aliyun.alink.devicesdk.demo:layout/zxl_capture: Error inflating class androidx.camera.view.PreviewView

3.     java.lang.NoSuchMethodError: No static method metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; in class Ljava/lang/invoke/LambdaMetafactory; or its super classes (declaration of 'java.lang.invoke.LambdaMetafactory' appears in /apex/com.android.art/javalib/core-oj.jar)

**Comment by jenly1314** [comment]
请查看REAME中 [JDK版本](https://github.com/jenly1314/ZXingLite#jdk%E7%89%88%E6%9C%AC) 
需使用JDK8+编译，在你项目中的build.gradle的android{}中添加配置：
```
compileOptions {
    targetCompatibility JavaVersion.VERSION_1_8
    sourceCompatibility JavaVersion.VERSION_1_8
}
```

**Comment by Allen8Lee** [comment]
您发送的邮件我已收到。
