### ISSUE TITLE
扫描屏幕上的二维码，如果背景不是白色的，这时候扫码识别率不高

### ISSUE THREAD

**Issue by jinlongwu** [jenly1314/ZXingLite#221]
![image](https://github.com/jenly1314/ZXingLite/assets/9429605/23af151d-89f3-4101-bc3f-18eb9c2601f5)
1.暗黑模式下，我的二维码在屏幕上，如果是二维码在深色背景上，在地下室等光线暗的情况，识别率很低
2. setNeedAutoZoom(true)//二维码太小时可自动缩放，默认为false 不起作用

**Comment by jenly1314** [comment]
1. 识别率问题可参见说明：[#69](https://github.com/jenly1314/ZXingLite/issues/69#issuecomment-559710812)
2. setNeedAutoZoom(true) 这个配置肯定是有用的，需要满足一定的条件才会触发自动缩放，只是如果你不是连续扫码的话，这个配置就会显得很鸡肋。
