### ISSUE TITLE
扫码的时候 界面有多个二维码 如何给予提示  类似微信那种 让用户选择点击哪个？

### ISSUE THREAD

**Issue by will12190** [jenly1314/ZXingLite#222]

**Comment by jenly1314** [comment]
ZXingLite目前不支持一次识别多个码，所以没有这个功能；如果需要此功能你可以选择使用 [MLKit](https://github.com/jenly1314/MLKit) 或 [WeChatQRCode](https://github.com/jenly1314/WeChatQRCode)

**Comment by will12190** [comment]
这2个库也是您在维护吗？

**Comment by jenly1314** [comment]
> 这2个库也是您在维护吗？

对的，链接应该能直接看出来。

**Comment by will12190** [comment]
👍👍👍

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
