### ISSUE TITLE
前置预览颠倒， 怎么调整

### ISSUE THREAD

**Issue by mikedream89** [jenly1314/ZXingLite#229]

**Comment by mikedream89** [comment]
@jenly1314 @asdzheng

**Comment by Tj155** [comment]
我也出现了这个问题，咋改啊

**Comment by jenly1314** [comment]
不知道怎么个颠倒法； 首先Camera相关部分是基于CameraX来实现的，所以关于Camera相关配置，完全遵循Camerax配置方式；直接看官方的CameraX相关配置说明即可；比如：[Camera旋转配置](https://developer.android.google.cn/training/camerax/configuration#rotation)；至于怎么将Camera的配置与扫码关联起来，可以参考[CameraScan](https://github.com/jenly1314/CameraScan)中关于**CameraConfig**的相关说明。
