### ISSUE TITLE
扫码速度的问题

### ISSUE THREAD

**Issue by Dawnton** [jenly1314/ZXingLite#23]
加签名release的apk扫码识别速度很快(DecodeHandler: Found barcode 时间平均为150~250ms)，但是debug后的app扫码识别速度就很慢(DecodeHandler: Found barcode 时间平均为2000ms)，请问是什么原因呢

**Comment by sunwen0402** [comment]
遇到同样的问题debug 3-5秒左右

**Comment by ronalmessi** [comment]
扫码速度太慢，至少要3-5秒

**Comment by tanzhihao1qaz** [comment]
我也有这个debug模式下扫码慢的问题，而且我发现只要扫码页面重新打开几次，扫码速度又恢复了
