### ISSUE TITLE
camerax预览出现慢

### ISSUE THREAD

**Issue by pandans** [jenly1314/ZXingLite#230]
测试过程中发现 camerax 比之前surface 预览 黑屏时间长很多，让人感觉界面就是慢的，camerax就是慢些还是特定手机问题？

**Comment by jenly1314** [comment]
看日志分析原因；看是否是类似的问题：[https://github.com/jenly1314/MLKit/issues/32](https://github.com/jenly1314/MLKit/issues/32)

**Comment by pandans** [comment]
> 看日志分析原因；看是否是类似的问题：[https://github.com/jenly1314/MLKit/issues/32](https://github.com/jenly1314/MLKit/issues/32)

相比可能延迟 0.5s左右，人眼还是感官挺明显的，有没有加快的手段。 另外还有一个问题，条形码的扫码如果把摄像头预览区域放小是不是相应会降低识别率

**Comment by jenly1314** [comment]
#69
