### ISSUE TITLE
希伯来语下，如果设置了vvLabelText，他的布局会有异常

### ISSUE THREAD

**Issue by AleckWei** [jenly1314/ZXingLite#231]
我的项目涉及多语言。其中一种是希伯来语，它是从右到左的文案方向的。
我在xml中设置了 vvLabelText 后，xml的预览就明显是往右边靠了，不是居中的。
![希伯来语异常](https://github.com/jenly1314/ZXingLite/assets/39803802/ddfe29da-d640-4cff-abb0-ac38c41d3361)

**Comment by AleckWei** [comment]
版本号是最新的 3.0.1

**Comment by jenly1314** [comment]
> 我的项目涉及多语言。其中一种是希伯来语，它是从右到左的文案方向的。 我在xml中设置了 vvLabelText 后，xml的预览就明显是往右边靠了，不是居中的。 ![希伯来语异常](https://private-user-images.githubusercontent.com/39803802/286839134-ddfe29da-d640-4cff-abb0-ac38c41d3361.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MTExODAsIm5iZiI6MTcwMTQxMDg4MCwicGF0aCI6Ii8zOTgwMzgwMi8yODY4MzkxMzQtZGRmZTI5ZGEtZDY0MC00Y2ZmLWFiYjAtYWMzOGM0MWQzMzYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDA2MDgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1ZjIxMmFkMWYyZWJjZDliOTBjYzM3ZDk4NDA0OTVlZjQ2NGVmODQ0ZGJiMDlhZjhkY2VlYzc2YzViYWRiMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._fqXdBjmB7u7FfWzTuEvfFmDz6kmrnXsw8fxCIyyO-Q)

目前 **LabelText** 的内容只是简单的通过 **draw** 绘制显示的，如果你对此有更多的要求，完全可以使用 **TextView**，直接将 **TextView**盖在布局上来显示你的文本信息即可规避此问题。

**Comment by jenly1314** [comment]
> emmm，我也试过使用TextView去覆盖在ViewFinderView上面，但是好像没法完美适配到扫描框的下方。你这里有什么好的办法吗？

有的，我也是换算的；你只需要知道屏幕的宽高，扫描框的高度（默认为：screenWidth * vvFrameRatio；vvFrameRatio默认值为：0.625）和扫描框的位置（默认：居中）就能换算出来提示内容的具体位置。

**Comment by AleckWei** [comment]
> > emmm，我也试过使用TextView去覆盖在ViewFinderView上面，但是好像没法完美适配到扫描框的下方。你这里有什么好的办法吗？
> 
> 有的，我也是换算的；你只需要知道屏幕的宽高，扫描框的高度（默认为：screenWidth * vvFrameRatio；vvFrameRatio默认值为：0.625）和扫描框的位置（默认：居中）就能换算出来提示内容的具体位置。

了解了，那我往这个方向上试试

**Comment by AleckWei** [comment]
ok，按照大佬提供的思路解决了
