### ISSUE TITLE
升级到2.2.1以后,oppo手机扫码无反应

### ISSUE THREAD

**Issue by MYaoDan** [jenly1314/ZXingLite#234]
原来implementation 'com.king.zxing:zxing-lite:1.1.9-androidx'该机型没问题
升级到2.2.1版本后扫码无反应
![error](https://github.com/jenly1314/ZXingLite/assets/20011299/b0c6b87f-f21e-4af9-a008-a0c34db00671)
![Uploading 手机机型.jpg…]()

**Comment by MYaoDan** [comment]
![Uploading 手机机型.jpg…]()

**Comment by MYaoDan** [comment]
![Uploading 手机机型.png…]()

**Comment by MYaoDan** [comment]
但是1.1.9在另一个手机OPPO上有问题

**Comment by jenly1314** [comment]
你后面发的图裂了，没多少有用的信息；你通过在 **README** 页先下载演示App进行测试看是否正常。

**Comment by jenly1314** [comment]
#69
