### ISSUE TITLE
隐私政策合规问题

### ISSUE THREAD

**Issue by nopointer** [jenly1314/ZXingLite#237]
现在收到了“广东省APP安全生态联盟”发送的邮件，邮件里面说getSensorList()方法存在违规收集用户信息，但是您的sdk没有隐私政策文档说明吧？

--App未见向用户明示分享的第三方名称、目的及个人信息类型，用户同意隐私政策后，存在将传感器信息发送给zxing第三方SDK的行为

**Comment by jenly1314** [comment]
> 现在收到了“广东省APP安全生态联盟”发送的邮件，邮件里面说getSensorList()方法存在违规收集用户信息，但是您的sdk没有隐私政策文档说明吧？
> 
> --App未见向用户明示分享的第三方名称、目的及个人信息类型，用户同意隐私政策后，存在将传感器信息发送给zxing第三方SDK的行为

有用到光照传感器，用于检测光照强度，根据光照强度的值来判定是否需要闪光灯；这个你在App隐私政策里面说明用途即可。

**Comment by nopointer** [comment]
但是他会要求填写一个关于隐私政策的网页说明呢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月30日(周六) 下午2:19
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jenly1314/ZXingLite] 隐私政策合规问题 (Issue #237)




  
现在收到了“广东省APP安全生态联盟”发送的邮件，邮件里面说getSensorList()方法存在违规收集用户信息，但是您的sdk没有隐私政策文档说明吧？
 
--App未见向用户明示分享的第三方名称、目的及个人信息类型，用户同意隐私政策后，存在将传感器信息发送给zxing第三方SDK的行为
  
有用到光照传感器，用于检测光照强度，根据光照强度的值来判定是否需要闪光灯；这个你在App隐私政策里面说明用途即可。
