### ISSUE TITLE
荣耀手机扫码失败

### ISSUE THREAD

**Issue by gt562559842** [jenly1314/ZXingLite#238]
使用的库版本为：'com.github.jenly1314:zxing-lite:2.2.1'
手机型号：荣耀畅玩30（安卓12）：
![微信图片_20240104155241](https://github.com/jenly1314/ZXingLite/assets/18594219/f47a5727-339d-44db-a90a-94941bbb3185)
能进入扫码界面，但是没法扫码成功，因为是线上遇到的情况，无法看日志
是不是因为库版本太低的原因？

**Comment by jenly1314** [comment]
可能是，如果可以，请尽量使用最新版本；目前最新版本是：3.1.0；看你使用的2.x版本，升级至3.x可能需要改少量代码，如果不想改代码，就更新至2.x最新版本。

**Comment by ld15232066412** [comment]
老哥解决了吗？碰到同样的问题了。

**Comment by jenly1314** [comment]
> 老哥解决了吗？碰到同样的问题了。

readme页面下载演示App测试扫码是否正常，再来反馈。

**Comment by ld15232066412** [comment]
又碰到个华为，和荣耀一样，下载作者大佬提供的演示App，也是扫码没反应，因为全生产环境碰到的，没法测试，难搞

**Comment by jenly1314** [comment]
> 又碰到个华为，和荣耀一样，下载作者大佬提供的演示App，也是扫码没反应，因为全生产环境碰到的，没法测试，难搞

反馈问题时不提供关键信息，怎么去重现与定位？无效的反馈毫无意义。

**Comment by jenly1314** [comment]
#69

**Comment by jenly1314** [comment]
#69
