### ISSUE TITLE
微信二维码如果是白色样式，扫码识别不了

### ISSUE THREAD

**Issue by sanyuanzhang** [jenly1314/ZXingLite#239]
场景：扫微信二维码名片，换成白色样式的二维码，无法识别，黑色的可以识别

**Comment by jenly1314** [comment]
> 场景：扫微信二维码名片，换成白色样式的二维码，无法识别，黑色的可以识别

参见：[DecodeConfig.setSupportLuminanceInvert(boolean)](https://javadoc.jitpack.io/com/github/jenly1314/ZXingLite/3.1.0/javadoc/com/king/zxing/DecodeConfig.html#setSupportLuminanceInvert(boolean))
