### ISSUE TITLE
无法识别  DATA_MATRIX 格式的二维码

### ISSUE THREAD

**Issue by xiaolingcong** [jenly1314/ZXingLite#240]
无法识别  DATA_MATRIX 格式的二维码

**Comment by jenly1314** [comment]
你都没配置，怎么识别？参见文档：[DecodeConfig.setHints(Map)](https://javadoc.jitpack.io/com/github/jenly1314/ZXingLite/3.1.0/javadoc/com/king/zxing/DecodeConfig.html#setHints(Map))
