### ISSUE TITLE
无法设置仅识别条形码

### ISSUE THREAD

**Issue by lyl15151865258** [jenly1314/ZXingLite#241]
通过DecodeConfig的setHints()方法，设置识别的编码类型，无论如何设置，要么只能识别二维码，要么二维码和条形码一起识别，无法只设置识别条形码，尽管在代码中设置了decodeConfig.setHints(DecodeFormatManager.CODE_128_HINTS)，依然不能识别条形码，反而可以识别二维码。

**Comment by Allen8Lee** [comment]
您发送的邮件我已收到。

**Comment by lyl15151865258** [comment]
已解决，使用MultiFormatAnalyzer解析类即可
