### ISSUE TITLE
引用库拉不下来

### ISSUE THREAD

**Issue by SkeletonKing-SNK** [jenly1314/ZXingLite#243]
implementation 'com.github.jenly1314:zxing-lite:2.4.0'
应该是2.4.0库的依赖下不下来

* What went wrong:
Execution failed for task ':app:mergeDebugNativeLibs'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve androidx.camera:camera-core:1.2.1.
     Required by:
         project :app > com.github.jenly1314:zxing-lite:2.4.0
      > Could not resolve androidx.camera:camera-core:1.2.1.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/androidx/camera/camera-core/1.2.1/camera-core-1.2.1.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/androidx/camera/camera-core/1.2.1/camera-core-1.2.1.pom'.
               > Remote host terminated the handshake
   > Could not resolve androidx.camera:camera-camera2:1.2.1.
     Required by:
         project :app > com.github.jenly1314:zxing-lite:2.4.0
      > Could not resolve androidx.camera:camera-camera2:1.2.1.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/androidx/camera/camera-camera2/1.2.1/camera-camera2-1.2.1.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/androidx/camera/camera-camera2/1.2.1/camera-camera2-1.2.1.pom'.
               > Remote host terminated the handshake
   > Could not resolve androidx.camera:camera-lifecycle:1.2.1.
     Required by:
         project :app > com.github.jenly1314:zxing-lite:2.4.0
      > Could not resolve androidx.camera:camera-lifecycle:1.2.1.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/androidx/camera/camera-lifecycle/1.2.1/camera-lifecycle-1.2.1.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/androidx/camera/camera-lifecycle/1.2.1/camera-lifecycle-1.2.1.pom'.
               > Remote host terminated the handshake
   > Could not resolve androidx.camera:camera-view:1.2.1.
     Required by:
         project :app > com.github.jenly1314:zxing-lite:2.4.0
      > Could not resolve androidx.camera:camera-view:1.2.1.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/androidx/camera/camera-view/1.2.1/camera-view-1.2.1.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/androidx/camera/camera-view/1.2.1/camera-view-1.2.1.pom'.
               > Remote host terminated the handshake

**Comment by jenly1314** [comment]
这种网络问题，跟本库没关系；访问不google仓库，不行就用镜像仓库。

**Comment by SkeletonKing-SNK** [comment]
我用了vpn也不行  网页访问google都是可以的

**Comment by SkeletonKing-SNK** [comment]
搞好了  3q
