### ISSUE TITLE
stopCamera的Anr问题

### ISSUE THREAD

**Issue by DeveloperZH** [jenly1314/ZXingLite#246]
在BaseCameraScan类中stopCamera方法中 mCameraProviderFuture.get()是耗时的，这个可能会导致anr，应该咋处理

**Comment by jenly1314** [comment]
> 在BaseCameraScan类中stopCamera方法中 mCameraProviderFuture.get()是耗时的，这个可能会导致anr，应该咋处理

你是怎么使用的？相关日志呢？
