### ISSUE TITLE
无法扫描部分Data Matrix格式的二维码

### ISSUE THREAD

**Issue by zhclwr** [jenly1314/ZXingLite#247]
<img width="390" alt="image" src="https://github.com/jenly1314/ZXingLite/assets/25841153/dca02a86-2a90-4a92-8151-7875af1b8b57">

上面这种是可以正确扫码并给出正确结果的

![image](https://github.com/jenly1314/ZXingLite/assets/25841153/50b98586-5f35-4ede-9ae8-c0e58cb095d1)

这种扫出来的结果不对，每次扫的结果也不一样，偶尔甚至扫不出来，正确结果应该是右侧的数字
微信倒是可以扫出来的

以下为主要代码
```java
public Analyzer<Result> createAnalyzer() {
      //初始化解码配置
      DecodeConfig decodeConfig = new DecodeConfig();
      decodeConfig.setHints(DecodeFormatManager.ALL_HINTS)
              .setFullAreaScan(false)//设置是否全区域识别，默认false
              .setAreaRectRatio(1f)//设置识别区域比例，默认0.8，设置的比例最终会在预览区域裁剪基于此比例的一个矩形进行扫码识别
              .setAreaRectVerticalOffset(0)//设置识别区域垂直方向偏移量，默认为0，为0表示居中，可以为负数
              .setAreaRectHorizontalOffset(0);//设置识别区域水平方向偏移量，默认为0，为0表示居中，可以为负数
      // BarcodeCameraScanActivity默认使用的MultiFormatAnalyzer，这里可以改为使用QRCodeAnalyzer
      return new MultiFormatAnalyzer(decodeConfig);
  }

```

**Comment by jenly1314** [comment]
#69

**Comment by zhclwr** [comment]
我下载了[MLKit](https://github.com/jenly1314/MLKit) 和 [WeChatQRCode](https://github.com/jenly1314/WeChatQRCode) 的示例app，都无法识别下面的二维码

**Comment by zhclwr** [comment]
> #69

我下载了[MLKit](https://github.com/jenly1314/MLKit) 和 [WeChatQRCode](https://github.com/jenly1314/WeChatQRCode) 的示例app，都无法识别下面的二维码
