### ISSUE TITLE
从相册选择图片解析二维码耗时长

### ISSUE THREAD

**Issue by yingka** [jenly1314/ZXingLite#248]
zxing-lite:3.1.1版本，demo里使用CodeUtils.parseCode(bitmap);从相册选择图片解析二维码，耗时大概1秒，集成到项目里，同样的代码，解析耗时8秒+，几款机型都试了，不知道哪里的问题？

**Comment by yingka** [comment]
还有个相关的问题，同一个二维码，从相册选择识别结果为null，扫描能识别出结果，怎么解决呢

**Comment by jenly1314** [comment]
> zxing-lite:3.1.1版本，demo里使用CodeUtils.parseCode(bitmap);从相册选择图片解析二维码，耗时大概1秒，集成到项目里，同样的代码，解析耗时8秒+，几款机型都试了，不知道哪里的问题？



> zxing-lite:3.1.1版本，demo里使用CodeUtils.parseCode(bitmap);从相册选择图片解析二维码，耗时大概1秒，集成到项目里，同样的代码，解析耗时8秒+，几款机型都试了，不知道哪里的问题？

`CodeUtils.parseCode(bitmap);` 本身就是耗时操作，不要直接在主线程执行。demo应该有代码示例的。

**Comment by jenly1314** [comment]
> 还有个相关的问题，同一个二维码，从相册选择识别结果为null，扫描能识别出结果，怎么解决呢

[#197](https://github.com/jenly1314/ZXingLite/issues/197#issuecomment-1193682617)

**Comment by yingka** [comment]
> > zxing-lite:3.1.1版本，demo里使用CodeUtils.parseCode(bitmap);从相册选择图片解析二维码，耗时大概1秒，集成到项目里，同样的代码，解析耗时8秒+，几款机型都试了，不知道哪里的问题？
> 
> > zxing-lite:3.1.1版本，demo里使用CodeUtils.parseCode(bitmap);从相册选择图片解析二维码，耗时大概1秒，集成到项目里，同样的代码，解析耗时8秒+，几款机型都试了，不知道哪里的问题？
> 
> `CodeUtils.parseCode(bitmap);` 本身就是耗时操作，不要直接在主线程执行。demo应该有代码示例的。


是在子线程执行的。而且缩小解析编码类型也试了，快1-2秒，但是整体解析时间还是很长，必现的问题
![image](https://github.com/jenly1314/ZXingLite/assets/20808020/a953b0a6-d437-4f0f-a6e9-361084331539)
