### ISSUE TITLE
如何正确设置扫码框的边角为矩形带圆角？

### ISSUE THREAD

**Issue by PengShaoLei97** [jenly1314/ZXingLite#253]
**效果图：**

![image](https://github.com/user-attachments/assets/92c76e2b-3f02-4e2e-994c-a15d6135fdc6)

LaserDrawable 和 FrameDrawable 并不能实现我预期的效果。

请问是否有可行的解决方案？

**Comment by Allen8Lee** [comment]
您发送的邮件我已收到。

**Comment by jenly1314** [comment]
> **效果图：**
> 
> ![image](https://private-user-images.githubusercontent.com/49141931/356189468-92c76e2b-3f02-4e2e-994c-a15d6135fdc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNzUxNjIsIm5iZiI6MTcyMzE3NDg2MiwicGF0aCI6Ii80OTE0MTkzMS8zNTYxODk0NjgtOTJjNzZlMmItM2YwMi00ZTJlLTk5NGMtYTE1ZDYxMzVmZGM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDAzNDEwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwMzgwZWM0MGQ5Y2JlNWExYjY3Y2RkYmFhNDU4ZDg2Zjk1ZDE2ZTQ0ZTg0MDlmZWQyNzMzM2YzYzg1NzEzY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kADLwlN8VsD1owbZM3eJ_g8bRN0b5DqQsqaENIjngA8)
> 
> LaserDrawable 和 FrameDrawable 并不能实现我预期的效果。
> 
> 请问是否有可行的解决方案？

还在用`v2.x`的旧版本吗？可参见：[ViewfinderView](https://github.com/jenly1314/ViewfinderView)

**Comment by PengShaoLei97** [comment]
@jenly1314 不是，我使用的是最新的版本：3.2.0，如果我要是先这种圆角边角，有对应的方法可以设置吗？

![image](https://github.com/user-attachments/assets/ce5caf55-20dc-4c69-a638-d62ae8ff9c42)

**Comment by PengShaoLei97** [comment]
> > **效果图：**
> > ![image](https://private-user-images.githubusercontent.com/49141931/356189468-92c76e2b-3f02-4e2e-994c-a15d6135fdc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNzUxNjIsIm5iZiI6MTcyMzE3NDg2MiwicGF0aCI6Ii80OTE0MTkzMS8zNTYxODk0NjgtOTJjNzZlMmItM2YwMi00ZTJlLTk5NGMtYTE1ZDYxMzVmZGM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDAzNDEwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwMzgwZWM0MGQ5Y2JlNWExYjY3Y2RkYmFhNDU4ZDg2Zjk1ZDE2ZTQ0ZTg0MDlmZWQyNzMzM2YzYzg1NzEzY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kADLwlN8VsD1owbZM3eJ_g8bRN0b5DqQsqaENIjngA8)
> > LaserDrawable 和 FrameDrawable 并不能实现我预期的效果。
> > 请问是否有可行的解决方案？
> 
> 还在用`v2.x`的旧版本吗？可参见：[ViewfinderView](https://github.com/jenly1314/ViewfinderView)

确实可以通过 vvFrameDrawable 设置去实现，只是后续会不会支持设置圆角边角的属性呢？我很好奇。

**Comment by PengShaoLei97** [comment]
感谢。
