### ISSUE TITLE
使用 vvLaserDrawable 方法设置扫描线图片时，设置的内容会超出扫描框的设定范围。

### ISSUE THREAD

**Issue by PengShaoLei97** [jenly1314/ZXingLite#254]
**描述：**

在使用 vvLaserDrawable 设置了扫描线的图片后，图片会错误的加载到扫描框之外的区域。

**现象：**

![image](https://github.com/user-attachments/assets/3f528fc6-03bd-4b27-bfa7-3e7b28e53c20)

**相关代码：**

![image](https://github.com/user-attachments/assets/7a00865f-cbeb-4ba4-a241-e1314a90db90)

**Comment by jenly1314** [comment]
> **描述：**
> 
> 在使用 vvLaserDrawable 设置了扫描线的图片后，图片会错误的加载到扫描框之外的区域。
> 
> **现象：**
> 
> ![image](https://private-user-images.githubusercontent.com/49141931/357431581-3f528fc6-03bd-4b27-bfa7-3e7b28e53c20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MDAyMTQsIm5iZiI6MTcyMzU5OTkxNCwicGF0aCI6Ii80OTE0MTkzMS8zNTc0MzE1ODEtM2Y1MjhmYzYtMDNiZC00YjI3LWJmYTctM2U3YjI4ZTUzYzIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDAxNDUxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyZDIwNmYzMjFjZDljZGNkY2MxNTA3ZmQxM2Q5NzFmZTYyOWJkZDkxN2Q2ZGIxNzIxZTZhZDk2OTU1MzNlNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YvRBM0Ae81M8S8IKaDRnoj8hR-Ru8AUP3UtbdeB-MY8)
> 
> **相关代码：**
> 
> ![image](https://private-user-images.githubusercontent.com/49141931/357432389-7a00865f-cbeb-4ba4-a241-e1314a90db90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MDAyMTQsIm5iZiI6MTcyMzU5OTkxNCwicGF0aCI6Ii80OTE0MTkzMS8zNTc0MzIzODktN2EwMDg2NWYtY2JlYi00YmE0LWEyNDEtZTEzMTRhOTBkYjkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDAxNDUxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiN2I1MTFiZGNkNmUwNzFlMWJiYzhkNjczMzRhNTA4MTkyZDJkZWQyN2Y3NjA4MGNjOWI1ZjBlODIyNjFlYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.udoRugNz3qa521v7oB4sXKyWmNirTDnV8oiCUowQp3k)

1. 你这个自定义的扫描线比默认的扫描线高出不少，需设置 `vvLaserLineHeight` ；
2. 提问提错地方了，  **ViewfinderView** 是一个独立维护的库，隶属于：[ViewfinderView](https://github.com/jenly1314/ViewfinderView)

**Comment by PengShaoLei97** [comment]
感谢解答，您提供的方案确实有用，但是在这之前我是通过重写 ViewfinderView 来实现的，具体代码如下：

自定义图片绘制：

![image](https://github.com/user-attachments/assets/8b9b82e1-8260-414e-910f-2c3a22cd66c0)

四周边角弧度+取景框圆角

`/**
     * 绘制边角
     */
    private void drawCorner(Canvas canvas, Rect frame) {
        // 保存画笔当前状态
        Paint.Style originalStyle = paint.getStyle();
        float originalStrokeWidth = paint.getStrokeWidth();
        int originalColor = paint.getColor();
        Paint.Cap originalCap = paint.getStrokeCap();

        // 设置画笔样式和颜色
        paint.setColor(frameCornerColor);
        paint.setStyle(Paint.Style.STROKE); // 使用描边样式
        paint.setStrokeWidth(frameCornerStrokeWidth); // 设置线宽
        paint.setStrokeCap(Paint.Cap.ROUND); // 设置线条末端为圆角

        float cornerRadius = UtilKt.dp2Px(12);  // 设置你希望的圆角半径
        float cornerLength = frameCornerSize;  // 每条线的长度

        // 左上角
        canvas.drawArc(new RectF(frame.left, frame.top, frame.left + 2 * cornerRadius, frame.top + 2 * cornerRadius),
                180, 90, false, paint); // 画弧
        canvas.drawLine(frame.left + cornerRadius, frame.top, frame.left + cornerLength, frame.top, paint); // 水平线
        canvas.drawLine(frame.left, frame.top + cornerRadius, frame.left, frame.top + cornerLength, paint); // 垂直线

        // 右上角
        canvas.drawArc(new RectF(frame.right - 2 * cornerRadius, frame.top, frame.right, frame.top + 2 * cornerRadius),
                270, 90, false, paint); // 画弧
        canvas.drawLine(frame.right - cornerRadius, frame.top, frame.right - cornerLength, frame.top, paint); // 水平线
        canvas.drawLine(frame.right, frame.top + cornerRadius, frame.right, frame.top + cornerLength, paint); // 垂直线

        // 左下角
        canvas.drawArc(new RectF(frame.left, frame.bottom - 2 * cornerRadius, frame.left + 2 * cornerRadius, frame.bottom),
                90, 90, false, paint); // 画弧
        canvas.drawLine(frame.left + cornerRadius, frame.bottom, frame.left + cornerLength, frame.bottom, paint); // 水平线
        canvas.drawLine(frame.left, frame.bottom - cornerRadius, frame.left, frame.bottom - cornerLength, paint); // 垂直线

        // 右下角
        canvas.drawArc(new RectF(frame.right - 2 * cornerRadius, frame.bottom - 2 * cornerRadius, frame.right, frame.bottom),
                0, 90, false, paint); // 画弧
        canvas.drawLine(frame.right - cornerRadius, frame.bottom, frame.right - cornerLength, frame.bottom, paint); // 水平线
        canvas.drawLine(frame.right, frame.bottom - cornerRadius, frame.right, frame.bottom - cornerLength, paint); // 垂直线

        // 重置画笔状态
        paint.setStyle(originalStyle);
        paint.setStrokeWidth(originalStrokeWidth);
        paint.setColor(originalColor);
        paint.setStrokeCap(originalCap);
    }`

`/**
     * 绘制模糊区域
     */
    private void drawExterior(Canvas canvas, Rect frame, int width, int height) {
        if (maskColor != 0) {
            // 绘制整个模糊区域
            paint.setColor(maskColor);
            canvas.drawRect(0, 0, width, height, paint);
            // 设置混合模式为清除
            paint.setXfermode(new PorterDuffXfermode(PorterDuff.Mode.CLEAR));
            // 绘制圆角矩形的取景区域
            float cornerRadius = UtilKt.dp2Px(12);
            canvas.drawRoundRect(
                    new RectF(frame.left, frame.top, frame.right, frame.bottom),
                    cornerRadius, cornerRadius, paint
            );
            // 清除混合模式
            paint.setXfermode(null);
        }
    }`
