### ISSUE TITLE
生成二维码如何设置背景色

### ISSUE THREAD

**Issue by CFSB** [jenly1314/ZXingLite#256]
目前只有白色背景色，我父布局定义了一个渐变的背景色作为背景，但是默认的白色背景无法设置为透明

**Comment by jenly1314** [comment]
绘制二维码就那几句代码，具体可参见：[CodeUtils](https://github.com/jenly1314/ZXingLite/blob/master/zxing-lite/src/main/java/com/king/zxing/util/CodeUtils.java#L172-L204)；想要透明背景可以自己稍微改下；
