### ISSUE TITLE
怎么实现全屏扫码

### ISSUE THREAD

**Issue by zhyang18** [jenly1314/ZXingLite#27]
你好！怎么样实现全屏扫码，不仅限制于扫码框内。

**Comment by jenly1314** [comment]
想实现全屏，将扫码时抓取数据的范围修改为屏幕的宽高就行。个人并不建议全屏扫码，因为在性能与扫码速度之间需做一定的取舍。ZXingLite就是做了一定的取舍，趋于二者之间，不在框内也能扫码，但非全屏识别，既保证识别速度，也保证性能的损耗。

**Comment by zhyang18** [comment]
谢谢回答，修改了源代码，改成了全屏识别
