### ISSUE TITLE
开启连续扫描会有一个逻辑上的bug

### ISSUE THREAD

**Issue by nongchengqi** [jenly1314/ZXingLite#29]
/**
     * 接收扫码结果，想支持连扫时，可将{@link #continuousScan(boolean)}设置为{@code true}
     * 如果{@link #isContinuousScan}支持连扫，则默认重启扫码和解码器；当连扫逻辑太复杂时，
     * 请将{@link #autoRestartPreviewAndDecode(boolean)}设置为{@code false}，并手动调用{@link #restartPreviewAndDecode()}
     * @param result 扫码结果
     */
    public void onResult(Result result){
        String text = result.getText();
        if(isContinuousScan){
            if(isAutoRestartPreviewAndDecode){
                if(onCaptureCallback!=null){
                    onCaptureCallback.onResultCallback(text);
                }
                restartPreviewAndDecode();
            }
        }else{
            //如果设置了回调，并且onCallback返回为true，则表示拦截
            if(onCaptureCallback!=null && onCaptureCallback.onResultCallback(text)){
                return;
            }
            Intent intent = new Intent();
            intent.putExtra(Intents.Scan.RESULT,text);
            activity.setResult(Activity.RESULT_OK,intent);
            activity.finish();
        }
    }

这是您原来的处理，但是如果我开启连续扫描，并且禁止自动重启下次扫描，您就不会回调结果了。应该修改为
 public void onResult(Result result){
        String text = result.getText();
        if(isContinuousScan){
              if(onCaptureCallback!=null){
                    onCaptureCallback.onResultCallback(text);
                }
            if(isAutoRestartPreviewAndDecode){
                //if(onCaptureCallback!=null){
               //     onCaptureCallback.onResultCallback(text);
               // }
                restartPreviewAndDecode();
            }
        }else{
          ...
        }
}

**Comment by jenly1314** [comment]
并非Bug，设计初衷就是如此，你可以通过改变isAutoRestartPreviewAndDecode值来自动重置预览。
方法上面的注释已经很清楚的说明了。

**Comment by nongchengqi** [comment]
public void onResult(Result result){
    String text = result.getText();
    if(isContinuousScan){
        if(isAutoRestartPreviewAndDecode){
            if(onCaptureCallback!=null){
                onCaptureCallback.onResultCallback(text);
            }
            restartPreviewAndDecode();
        }
    }else{
        ...
}

可能是我表达不清楚，我说如果我开启连续扫描，并且禁止自动重启下次扫描，也就是上面的onResult方法里面isContinuousScan=true,但是isAutoRestartPreviewAndDecode=false,那么您没有回调扫描结果 onCaptureCallback.onResultCallback(text);，导致无法处理扫描结果

**Comment by jenly1314** [comment]
嗯、确实有这么个问题、抽空我改下、把回调提到外面去，暂时你可以通过重写onResult方法规避、
