### ISSUE TITLE
混淆问题

### ISSUE THREAD

**Issue by Forest0924** [jenly1314/ZXingLite#31]
没有说需要混淆规则
但混淆报错了

**Comment by getglory** [comment]
> 没有说需要混淆规则
> 但混淆报错了

我用的自己的Activity，好像没配置没问题。看看报哪些类找不到，如果是zxing相关的类，加上这些试试：
-keep class com.google.zxing.{ *;}
-dontwarn com.google.zxing.**

-dontwarn com.king.zxing.**
-keep com.king.zxing.*{ *;}

**Comment by BrightVan** [comment]
zxing不需要配置混淆规则，该库也不用，出了问题，可能是基本的混淆规则没配；androidx，support库都是自带混淆规则，也不需要keep，网上的很多教程有些误人子弟，全都keep，编译后dex会大不少，1M以上。
#-------------------------------------基本配置-不能被混淆的--------------------------------------------
-keep public class * extends android.app.Activity
-keep public class * extends android.app.Fragment
-keep public class * extends android.app.Application
-keep public class * extends android.app.Service
-keep public class * extends android.content.BroadcastReceiver
-keep public class * extends android.content.ContentProvider
-keep public class * extends android.app.backup.BackupAgentHelper
-keep public class * extends android.preference.Preference
-keep public class * extends androidx.fragment.app.Fragment
#这个应该是Google play相关的
-keep public class com.android.vending.licensing.ILicensingService

#保持枚举enum类不被混淆
-keepclassmembers enum * {
  public static **[] values();
 public static ** valueOf(java.lang.String);
}
#这个主要是在layout 中写的onclick方法android:onclick="onClick"，不进行混淆
-keepclassmembers class * extends android.app.Activity {
   public void *(android.view.View);
}
#自定义组件不被混淆
-keep public class * extends android.view.View {
    public <init>(android.content.Context);
    public <init>(android.content.Context, android.util.AttributeSet);
    public <init>(android.content.Context, android.util.AttributeSet, int);
    public void set*(...);
}
#保持 native 方法不被混淆
-keepclasseswithmembernames class * {
        native <methods>;
}
#保持 Parcelable 不被混淆
-keep class * implements android.os.Parcelable {
      public static final android.os.Parcelable$Creator *;
}
#不混淆资源类
-keepclassmembers class **.R$* {
      public static <fields>;
}
#保持注解继承类不混淆
-keep class * extends java.lang.annotation.Annotation {*;}
#保持Serializable实现类不被混淆
-keepnames class * implements java.io.Serializable
#保持Serializable不被混淆并且enum 类也不被混淆
-keepclassmembers class * implements java.io.Serializable {
    static final long serialVersionUID;
    private static final java.io.ObjectStreamField[] serialPersistentFields;
    private void writeObject(java.io.ObjectOutputStream);
    private void readObject(java.io.ObjectInputStream);
    java.lang.Object writeReplace();
    java.lang.Object readResolve();
}

**Comment by Forest0924** [comment]
> > 没有说需要混淆规则
> > 但混淆报错了
> 
> 我用的自己的Activity，好像没配置没问题。看看报哪些类找不到，如果是zxing相关的类，加上这些试试：
> -keep class com.google.zxing.{ _;} -dontwarn com.google.zxing._*
> 
> -dontwarn com.king.zxing.**
> -keep com.king.zxing.*{ *;}

已经解决，是我自己支持库混淆错了。

**Comment by Forest0924** [comment]
> zxing不需要配置混淆规则，该库也不用，出了问题，可能是基本的混淆规则没配；androidx，support库都是自带混淆规则，也不需要keep，网上的很多教程有些误人子弟，全都keep，编译后dex会大不少，1M以上。
> #-------------------------------------基本配置-不能被混淆的--------------------------------------------
> -keep public class * extends android.app.Activity
> -keep public class * extends android.app.Fragment
> -keep public class * extends android.app.Application
> -keep public class * extends android.app.Service
> -keep public class * extends android.content.BroadcastReceiver
> -keep public class * extends android.content.ContentProvider
> -keep public class * extends android.app.backup.BackupAgentHelper
> -keep public class * extends android.preference.Preference
> -keep public class * extends androidx.fragment.app.Fragment
> #这个应该是Google play相关的
> -keep public class com.android.vending.licensing.ILicensingService
> 
> #保持枚举enum类不被混淆
> -keepclassmembers enum * {
> public static **[] values();
> public static ** valueOf(java.lang.String);
> }
> #这个主要是在layout 中写的onclick方法android:onclick="onClick"，不进行混淆
> -keepclassmembers class * extends android.app.Activity {
> public void _(android.view.View); } #自定义组件不被混淆 -keep public class * extends android.view.View { public (android.content.Context); public (android.content.Context, android.util.AttributeSet); public (android.content.Context, android.util.AttributeSet, int); public void set_(...);
> }
> #保持 native 方法不被混淆
> -keepclasseswithmembernames class * {
> native ;
> }
> #保持 Parcelable 不被混淆
> -keep class * implements android.os.Parcelable {
> public static final android.os.Parcelable$Creator _; } #不混淆资源类 -keepclassmembers class *_.R$_ { public static ; } #保持注解继承类不混淆 -keep class * extends java.lang.annotation.Annotation {_;}
> #保持Serializable实现类不被混淆
> -keepnames class * implements java.io.Serializable
> #保持Serializable不被混淆并且enum 类也不被混淆
> -keepclassmembers class * implements java.io.Serializable {
> static final long serialVersionUID;
> private static final java.io.ObjectStreamField[] serialPersistentFields;
> private void writeObject(java.io.ObjectOutputStream);
> private void readObject(java.io.ObjectInputStream);
> java.lang.Object writeReplace();
> java.lang.Object readResolve();
> }

厉害了
