### ISSUE TITLE
1.1.0版本中com.king.zxing.CaptureActivity未注册到清单文件

### ISSUE THREAD

**Issue by allenli0413** [jenly1314/ZXingLite#32]
在1.1.0版本中报错，1.0.6版本中不会报这个错误
 2019-05-19 16:43:00.818 28466-28466/com.test.picture E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.test.picture, PID: 28466
    android.content.ActivityNotFoundException: Unable to find explicit activity class {com.test.picture/com.king.zxing.CaptureActivity}; have you declared this activity in your AndroidManifest.xml?
     需要自己注册：
<activity android:name="com.king.zxing.CaptureActivity"></activity>

**Comment by jenly1314** [comment]
特意去掉的，因为考虑到用户可能想使用非默认主题的缘故，如果使用到CaptureActivity，自己注册比较好。
