### ISSUE TITLE
识别二维码有问题，识别的数据错误，显示为05621335

### ISSUE THREAD

**Issue by chtrace** [jenly1314/ZXingLite#33]
识别二维码有问题，识别的数据错误，显示为05621335

**Comment by jenly1314** [comment]
请贴码

**Comment by cleanlavabo** [comment]
I got the same issue. I was trying to continuously scan the same QR code but it returned weird character sometimes (i.e: 12345678)

**Comment by cleanlavabo** [comment]
hi @jenly1314 , do you have any updates for this?

**Comment by jenly1314** [comment]
Sorry, I've been busy lately, I'm afraid I don't have much free time to deal with this problem. 
When I have spare time, I'll try my best to solve these problems.
