### ISSUE TITLE
ViewfinderView位置

### ISSUE THREAD

**Issue by onlycyndi** [jenly1314/ZXingLite#34]
你好，ViewfinderView位置是全屏固定的，可以让它自定义位置吗？

**Comment by jenly1314** [comment]
你想要的可能是修改扫码框位置，并非Camera的取景框位置，修改扫码框位置可通过padding相关属性来使扫码框偏移中心点。

**Comment by onlycyndi** [comment]
对的，试了下果然如此，没有来得及去看源码就问你这个，十分感谢。
