### ISSUE TITLE
固定焦距

### ISSUE THREAD

**Issue by onlycyndi** [jenly1314/ZXingLite#35]
你好，对焦还是不够快，我想给它固定一个焦距，条码和镜头在这个焦距内去扫描，减少对焦时间，不知道这样的构思和实现怎么样去调整。

**Comment by jenly1314** [comment]
想要固定焦距，可以通过captureHelper.supportAutoZoom(false);关闭自动变焦，然后调整自动对焦间隔时间。对于调整焦间隔时间：个人并不建议将对焦间隔时间调太短或者太长，这个需要自己斟酌。

**Comment by onlycyndi** [comment]
好的，谢谢，我试了下，效果挺好，就是费电和发烫。
