### ISSUE TITLE
扫描提示音bug

### ISSUE THREAD

**Issue by huyi3211** [jenly1314/ZXingLite#37]
synchronized void updatePrefs() {
        SharedPreferences prefs = PreferenceManager.getDefaultSharedPreferences(activity);
        shouldBeep(prefs, activity);
//        vibrate = prefs.getBoolean(Preferences.KEY_VIBRATE, false);
        if (playBeep && mediaPlayer == null) {
            // The volume on STREAM_SYSTEM is not adjustable, and users found it too loud,
            // so we now play on the music stream.
            activity.setVolumeControlStream(AudioManager.STREAM_MUSIC);
            mediaPlayer = buildMediaPlayer(activity);
        }
    }
初始化时，playBeep 一直是false；mediaPlayer 一直是null；根本不会有声音

**Comment by jenly1314** [comment]
请在onCreate方法中调用getCaptureHelper().playBeep(true)后，才会在CaptureHelper.onResume通过updatePrefs()初始化mediaPlayer
