### ISSUE TITLE
下面几个二维码几乎都扫不出来

### ISSUE THREAD

**Issue by lovelyelfpop** [jenly1314/ZXingLite#38]
但是微信能扫三个，支付宝全都可以

![1](https://user-images.githubusercontent.com/5656924/59317250-a6cef280-8cf4-11e9-8208-a2987b814a7c.png)
![2](https://user-images.githubusercontent.com/5656924/59317252-a7678900-8cf4-11e9-8b44-114ee987544e.png)
![3](https://user-images.githubusercontent.com/5656924/59317254-a7678900-8cf4-11e9-87e8-8f68f15fefe3.png)
![4](https://user-images.githubusercontent.com/5656924/59317255-a8001f80-8cf4-11e9-8208-7a5608d5ef31.png)

**Comment by jenly1314** [comment]
你贴的码扫不出来，主要原因是你发的二维码的“位置探测图形显示不全”和二维码“比较模糊”导致，这个需要做些特殊的处理才能识别。

**Comment by aowoWolf** [comment]
作者大大，我在草料网站上生成了一个 **hello world** 的二维码，也扫不出来结果

![image](https://user-images.githubusercontent.com/23431500/59667098-ba90c200-91e8-11e9-8310-c4c3a4db40ef.png)

**Comment by WWXXQQ** [comment]
> 你贴的码扫不出来，主要原因是你发的二维码的“位置探测图形显示不全”和二维码“比较模糊”导致，这个需要做些特殊的处理才能识别。

模糊的二维码做一个膨胀操作就可以识别出来了

**Comment by josephyuen** [comment]
这都是好的素材啊，检验库是否强大

**Comment by luoxiong94** [comment]
我们线上反馈很多码都识别不了, 最后老老实实用zxing, 就没啥问题了

**Comment by kamike** [comment]
卧槽，看到这里有一丝丝不敢用了

**Comment by jenly1314** [comment]
#69
