### ISSUE TITLE
提问，这个能识别弯曲的二维码吗

### ISSUE THREAD

**Issue by bubble96** [jenly1314/ZXingLite#39]
因为现在有需求，一些例如贴在电线杆或者曲面的上的二维码识别效率不高...

**Comment by getglory** [comment]
> 因为现在有需求，一些例如贴在电线杆或者曲面的上的二维码识别效率不高...

识别率高低是zxing的问题吧。。或者换zbar的项目试试看识别率有没提升。再不行就换其他库。这个库只是针对zxing的封装。。
