### ISSUE TITLE
androidx.appcompat 加载ViewfinderView报错

### ISSUE THREAD

**Issue by RhythmCoderZZF** [jenly1314/ZXingLite#43]
android.view.InflateException: Binary XML file line #22: Binary XML file line #22: Error inflating class com.king.zxing.ViewfinderView

**Comment by jenly1314** [comment]
目前并未适配AndroidX，后续有空支持AndroidX适配。

**Comment by jenly1314** [comment]
@RhythmCoderZZF   已支持AndroidX版本
