### ISSUE TITLE
你好，我用c生成的二维码，识别汉字为乱码，研究了几天，设置character为GKB都无改变，请教一下

### ISSUE THREAD

**Issue by AbsoluteChan** [jenly1314/ZXingLite#46]
CodeUtil.java
* 解析二维码图片
     * @param bitmapPath
     * @return
     */

    public static String parseQRCode(String bitmapPath) {
        Map<DecodeHintType, Object> hints = new HashMap<>();
        hints.put(DecodeHintType.CHARACTER_SET, "GBK");//"utf-8");
        return parseQRCode(bitmapPath,hints);
    }
decodeThread.java
if (characterSet != null) {
            hints.put(DecodeHintType.CHARACTER_SET, "GBK");
        }

**Comment by jenly1314** [comment]
这个取决于你生成二维码时用的是什么字符编码， 生成和解析用相同的字符编码就行。

**Comment by AbsoluteChan** [comment]
嗯，是这个道理，我编码的时候也是用的GKB，修改了解释码为GBK,中文依然是乱码，没有变化，所以咨询一下是不是我修改的代码位置问题

**Comment by jenly1314** [comment]
常用的字符编码就那么几个（UTF-8、GBK、GB2312、ISO8859-1），建议用UTF-8国际通用，你不妨贴个码，我抽空帮你定位下字符编码。

**Comment by AbsoluteChan** [comment]
之前我用基本的zxing，该二维码用GBK编码识别是可以 ，但是你这个版本识别该中文与出现乱码，C生成的二维码，我这里贴一下
![QQ截图20190717173435](https://user-images.githubusercontent.com/13114806/61369539-eaec7e80-a8c2-11e9-8e76-76fe2a7431c2.jpg)
我排除了下，发现你这个是自动识别编码然后选择识别的吗？
 如果我固定GBK应该可以排除这个错误。

**Comment by jenly1314** [comment]
你可以通过`CaptureHelper.characterSet(String characterSet);`来设置解码时的字符编码

**Comment by AbsoluteChan** [comment]
非常感谢，问题解决了，之前一直找不到哪里设定解码编码，原来你没有使用调用，而是自动适配的，现在我直接调用改方法，固定编码方式，问题解决了。
