### ISSUE TITLE
请问大佬这个二维码为什么识别不了呢？

### ISSUE THREAD

**Issue by okayFan** [jenly1314/ZXingLite#52]
![image](https://user-images.githubusercontent.com/20924164/62764186-debda080-babf-11e9-879d-b65dbb5a09a3.png)

**Comment by jenly1314** [comment]
方便提供生成二维码的一些参数配置吗？

**Comment by okayFan** [comment]
这个是工厂批量生产的，不是我们公司生产的码，我得去问问，他们说微信支付宝都能扫~很尴尬

**Comment by josephyuen** [comment]
兄弟这个码也牛逼呀

**Comment by KnIfER** [comment]
定位了下这码在ReedSolomonDecoder.java就错的时候抛出异常：
findErrorLocations()
 throw new ReedSolomonException("Error locator degree does not match number of roots");
强行注释掉的话，会发现返回结果里有很多乱码

**Comment by jenly1314** [comment]
#69
