### ISSUE TITLE
希望连续扫码增加可以配置时间间隔的参数

### ISSUE THREAD

**Issue by HoneyWorld** [jenly1314/ZXingLite#57]

**Comment by jenly1314** [comment]
连扫的场景，一般都需要在扫码后处理相应的逻辑，你可以在Activity或者Fragment的onCreate方法中通过`captureHelper.autoRestartPreviewAndDecode(false)`关闭自动重置扫码，然后在onResultCallback方法中接收结果回调，根据不同的扫码结果做完你的逻辑处理后，手动重置扫码`captureHelper.restartPreviewAndDecode(）`

**Comment by HoneyWorld** [comment]
谢谢楼主，实际场景有一些码扫描不出来
![1](https://user-images.githubusercontent.com/13584168/67665253-55be5300-f9a4-11e9-9465-2d5f210553c9.jpg)
![2](https://user-images.githubusercontent.com/13584168/67665254-55be5300-f9a4-11e9-96d2-58d5b0fc5d7c.jpg)
![3](https://user-images.githubusercontent.com/13584168/67665255-5656e980-f9a4-11e9-833a-03337a4d7bd9.jpg)
![4](https://user-images.githubusercontent.com/13584168/67665256-5656e980-f9a4-11e9-929d-d80eda17dd1f.jpg)

**Comment by jenly1314** [comment]
你贴的这些二维码的比例不对，二维码无法找到定位图案位置

**Comment by HoneyWorld** [comment]
@jenly1314 谢谢了，应该是码的问题
