### ISSUE TITLE
扫描失败回调问题

### ISSUE THREAD

**Issue by ender115** [jenly1314/ZXingLite#59]
请问有扫描失败的回调吗？我没有找到，比如无法识别等等情况

**Comment by jenly1314** [comment]
目前并未提供失败回调的方法，不知道你的需求是什么样的场景。所以不太清楚，你想要扫码失败回调的目的。只有一对一，识别图片时，才会知道成功与失败。
目前扫码流程：扫码时Camera是实时捕捉的，数据源在不断动态变化，存在失败的情况太多，失败后只是重置预览让继续扫码。
