### ISSUE TITLE
标题夸张了

### ISSUE THREAD

**Issue by 312353457** [jenly1314/ZXingLite#6]
固定资产的二维码，半天扫不出，扫了N次终于出来了，结果扫出来信息还是错误的。。。

**Comment by jenly1314** [comment]
这可能是ZXingLite库被黑的最惨的一次、

**Comment by 312353457** [comment]
说个实话怎么就是黑了呀，老哥，我最近在做扫码枪的东西，我现在做的扫略旧的固定资产二维码要很久才能成功。我看到你这标题媲美微信，心想应该会快，结果扫了半天扫不出来，扫出来一次，信息还是错误的 - -

**Comment by MichaelJokAr** [comment]
标题党了，
