### ISSUE TITLE
进入activity相机卡顿卡顿

### ISSUE THREAD

**Issue by INTKILOW** [jenly1314/ZXingLite#64]
进入activity相机卡顿卡顿

**Comment by liuleshuai** [comment]
顶一下，开启相机的时候确实有卡顿，试了好几个开源库都有这个问题。

**Comment by INTKILOW** [comment]
r如果有好的扫码库分享一下。

**Comment by liuleshuai** [comment]
我用的库还是这个，相对而言是最适合的，隔壁CZxing这个库没有卡顿，但是问题太多，而且维护是个问题。

**Comment by liuleshuai** [comment]
@jenly1314 麻烦关注下卡顿这个问题，复现方式：接入BlockCanary看一下就知道了
