### ISSUE TITLE
速度求优化哦

### ISSUE THREAD

**Issue by houyidg** [jenly1314/ZXingLite#65]
之前profile测试过打开相机和预览居然耗费300ms
现在线上的机型直接anr了：
信息：
用户 ID

unknown

发生时间

2019-11-21 18:12:46

上报时间

2019-11-21 18:12:48

使用时长

35 秒

前后台状态

前台

设备机型

VIVO X6PLUS A
系统版本

Android 5.0.2,level 21

ROM

vivo/FUNTOUCH

CPU架构

arm64-v8a

异常：
1 android.hardware.Camera._startPreview(Native Method)
--
2 android.hardware.Camera.startPreview(Camera.java:823)
3 com.king.zxing.a.d.startPreview(CameraManager.java:162)
4 com.king.zxing.c.<init>(CaptureHandler.java:73)
5 com.king.zxing.d.a(CaptureHelper.java:283)
6 com.king.zxing.d.a(CaptureHelper.java:46)
7 com.king.zxing.d$1.surfaceCreated(CaptureHelper.java:167)
8 android.view.SurfaceView.updateWindow(SurfaceView.java:579)
9 android.view.SurfaceView$3.onPreDraw(SurfaceView.java:176)
10 android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:847)
11 android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1989)
12 android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1079)
13 android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5839)
14 android.view.Choreographer$CallbackRecord.run(Choreographer.java:838)
15 android.view.Choreographer.doCallbacks(Choreographer.java:637)
16 android.view.Choreographer.doFrame(Choreographer.java:603)
17 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:824)
18 android.os.Handler.handleCallback(Handler.java:739)
19 android.os.Handler.dispatchMessage(Handler.java:95)
20 android.os.Looper.loop(Looper.java:135)
21 android.app.ActivityThread.main(ActivityThread.java:5318)
22 java.lang.reflect.Method.invoke(Native Method)
23 java.lang.reflect.Method.invoke(Method.java:372)
24 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:922)
25 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:717)

**Comment by houyidg** [comment]
# main(1)

Input dispatching timed out

ANR Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago. Wait queue length: 2. Wait queue head age: 18899.4ms.)

**Comment by jenly1314** [comment]
你这个可能需要具体的去定位下，是什么原因导致预览anr的
