### ISSUE TITLE
Jenly: ZXingLite正在征集使用者的信息，希望得到大家的支持🙏🙏🙏

### ISSUE THREAD

**Issue by jenly1314** [jenly1314/ZXingLite#68]
> **ZXingLite**从2018年中旬开源到现在，已经一年多了，经过这一年多不断的迭代，*ZXingLite*逐渐被更多的开发者使用和认可。欢迎直接进群 [![QQGroup](https://img.shields.io/badge/QQGroup-20867961-blue.svg)](http://shang.qq.com/wpa/qunwpa?idkey=8fcc6a2f88552ea44b1411582c94fd124f7bb3ec227e2a400dbbfaad3dc2f5ad)
 > 到目前为止：**ZXingLite**在 [JForg Bintray](https://bintray.com/beta/#/jenly/maven/zxing-lite?tab=overview) 的总下载量已达到**32W+**。在这期间感谢广大开发者的支持和提出的宝贵意见，让**ZXingLite**越来越完善，越来越好用。再此感谢大家！🙏🙏🙏

随着**ZXingLite**越来越完善，我们也鼓励更多的开发者去使用**ZXingLite**。为了增强他们使用的信心，现在向大家征集已经使用了**ZXingLite**的项目信息，希望得到大家的支持。信息格式如下：

```
- [x] 应用名称：
- [x] 公司官网/项目地址/应用下载地址：
```

> 复制上面格式并补全信息即可（公司官网，项目地址，应用下载地址选其一）

示例：
- [x] 应用名称：[EasyChat](https://fir.im/EasyChatAndroid)
- [x] 公司官网/项目地址/应用下载地址：https://github.com/yetel/EasyChatAndroidClient

**Comment by biglovesabor** [comment]
使用EAN_8和EAN_13生成二维码报错，错误信息为：Requested contents should be 8 digits long, but got 6

**Comment by mosentest** [comment]
这项目能上gp吗
