### ISSUE TITLE
关于Camera的问题

### ISSUE THREAD

**Issue by skytang168** [jenly1314/ZXingLite#7]
现在市面上的机器大部分都是5.0以上的了，5.0以上的Camera这个已经被标记过时了，能不能更换成Camera2.

**Comment by tanranran** [comment]
@skytang168 Camera2兼容性还不如Camera，国产机很多对于Camera2都有部分阉割

**Comment by SkyFlyTang** [comment]
哦 是这样啊 没研究这方面
