### ISSUE TITLE
作为library建议java1.7

### ISSUE THREAD

**Issue by chrism1981** [jenly1314/ZXingLite#80]
没仔细看到底源码里用里多少1.8的新特性，有一部分特性是需要手机api 大于24的。有一部分特性倒是不需要。 1.8的支持详见https://developer.android.com/studio/write/java8-support。 一般的app还是要兼容到api21的至少。 仅个人建议，酌情采纳。

**Comment by jenly1314** [comment]
目前 **Android API 16+** 即可使用ZXingLite，**README**上面有写，目前大部分项目基本都使用JDK8，Library要求使用**JDK8**并不过分，里面也只是使用JDK8的的部分特性。
