### ISSUE TITLE
ViewfinderView 设置了padding,扫描框确实偏移了，但是实际的识别区域并没有变，比如设置paddingBottom=“200dp”,实际操作中，识别区域还是屏幕中心

### ISSUE THREAD

**Issue by huangnan-hn** [jenly1314/ZXingLite#82]
题目中的问题困扰了我很久，希望能够有人提供些解决方法

**Comment by jenly1314** [comment]
`captureHelper.framingRectVerticalOffset(framingRectVerticalOffset);`
[API帮助文档](https://jenly1314.github.io/projects/ZXingLite/doc/)中的**CaptureHelper**类可以很明确的看到相关的参数配置
