### ISSUE TITLE
setManualCameraId(int cameraId) 方法如何调用？

### ISSUE THREAD

**Issue by feisher** [jenly1314/ZXingLite#83]
setManualCameraId(int cameraId) 方法如何调用？说是可以指定相机id,但是需要getCaptureHelper().getCameraManager() 才能用，但是调用getCaptureHelper的前提是拿到CaptureActivity，，必须继承CaptureActivity改写码？

**Comment by jenly1314** [comment]
README上面写的很清楚，快速实现扫码的几种方式，**Demo**中也有相应的示例

**Comment by feisher** [comment]
@jenly1314 看来demo果然是只能继承的方式才能修改(EasyCaptureActivity)，而不是跳转标准识别页面前有配置方法
