### ISSUE TITLE
黑屏、无法识别

### ISSUE THREAD

**Issue by zqlq4ever** [jenly1314/ZXingLite#89]
小米手机（android 7 android 10），三星手机（android 6），二维码经常一直扫不出。
这两种情况只要出现了，一段时间内清缓存，重启App，重装App，重启手机都无效。

**Comment by jenly1314** [comment]
请先下载[App Demo](https://raw.githubusercontent.com/jenly1314/ZXingLite/master/app/release/app-release.apk)试用，确认不是集成步骤的问题

**Comment by zqlq4ever** [comment]
> 请先下载[App Demo](https://raw.githubusercontent.com/jenly1314/ZXingLite/master/app/release/app-release.apk)试用，确认不是集成步骤的问题

 implementation 'com.king.zxing:zxing-lite:1.1.9-androidx'

 <activity
            android:name="com.king.zxing.CaptureActivity"
            android:screenOrientation="portrait" />

val scan = Intent(this, CaptureActivity::class.java)
startActivityForResult(scan, Constants.REQUEST_SCAN)

主要就是这3步,还是有时扫码无效

**Comment by jenly1314** [comment]
Camera没有动态授权吧，请参考Demo示例

**Comment by zqlq4ever** [comment]
> Camera没有动态授权吧，请参考Demo示例

黑屏那个是的，已经写了授权，扫不出来的就不清楚了，扫码页面已经出来了，摄像头正常可以看到内容

**Comment by zqlq4ever** [comment]
好像测试机问题，相机硬件坏了，时好时坏
