### ISSUE TITLE
CaptureActivity点击返回按钮黑屏

### ISSUE THREAD

**Issue by runryan** [jenly1314/ZXingLite#9]
有三个问题：

第一：在示例代码中`checkCameraPermissions`方法的返回值必须为`void`并且不能有参数，否则会有异常
> Cannot execute method [method name] because it is non-void method and/or has input parameters

第二：**首次**安装应用，给予相机权限，启动`EasyCaptureActivity`后，点击返回按钮，`EasyCaptureActivity`闪了一下，但是立马又显示出来了，再次点击返回按钮，才完全关闭`EasyCaptureActivity`

第三：我自己继承的`CaptureActivity`在**首次**启动后点击返回按钮，`EasyCaptureActivity`虽然扫描页面没了，但是留了个黑屏，再次点击才关闭`EasyCaptureActivity`;

之后再打开`CaptureActivity`，点击返回，一切正常；

**Comment by runryan** [comment]
我用的红米Note 4X 7.0的系统

**Comment by jenly1314** [comment]
已修改示例demo、
