### ISSUE TITLE
解析字符串时，头部出现﻿﻿"\uFEFF"，导致与真实字符串不一致

### ISSUE THREAD

**Issue by zqlq4ever** [jenly1314/ZXingLite#90]
图片是“男卫”的二维码，以及解析出来的实际结果

![男卫](https://user-images.githubusercontent.com/37474811/81266399-44eb4a00-9077-11ea-96d6-99cb9435d355.png)

![QQ截图20200507152704](https://user-images.githubusercontent.com/37474811/81266397-4452b380-9077-11ea-9895-09a803d94ba6.png)

**Comment by jenly1314** [comment]
你这是生成二维码的时候本身就带了**"\uFEFF"**不可见的非法字符，据我所知，排名比较靠前的草料二维码，在生成包含中文的二维码时就会有这个问题。你可以使用本库来生成二维码，或换个其他靠谱的二维码生成，然后扫码看看结果，

**Comment by zqlq4ever** [comment]
> 你这是生成二维码的时候本身就带了“\uFEFF”不可见的非法字符，据我所知，排名比较靠前的草料二维码，在生成包含中文的二维码时就会有这个问题。你可以使用本库来生成二维码，或换个其他靠谱的二维码生成，然后扫码看看结果，

原来如此，我使用的是草料二维码。以为是解码的结果带上的，临时方案是把结果的非法字符给去掉了。
