### ISSUE TITLE
可以无ui扫描吗？

### ISSUE THREAD

**Issue by KupoGu** [jenly1314/ZXingLite#94]
不打开扫描界面，类似影院取票机那样

**Comment by KnIfER** [comment]
可以啊，类似于无画面播放视频，不过为什么要无ui扫描呢？

**Comment by KnIfER** [comment]
其实不能……
`Preview will not actually start until a surface is supplied
     * with {@link #setPreviewDisplay(SurfaceHolder)} or
     * {@link #setPreviewTexture(SurfaceTexture)}.`
