### ISSUE TITLE
扫码框位置不够灵活

### ISSUE THREAD

**Issue by EthanCo** [jenly1314/ZXingLite#99]
扫码框位置不够灵活，比如我不想居中，想让扫码框固定在距离顶部多少距离的位置，就无法实现，用padding很难固定位置。

**Comment by dxy1046** [comment]
按照ViewFinderView自定义一份，然后再根据自己的布局调整CaptureHelper的偏移配置

**Comment by EthanCo** [comment]
谢谢 ~
